/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { User, User$inboundSchema } from "./user.js";

export type AuthResponse = {
  /**
   * JWT authentication token
   */
  token?: string | undefined;
  user?: User | undefined;
  expiresAt?: Date | undefined;
};

/** @internal */
export const AuthResponse$inboundSchema: z.ZodType<
  AuthResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  token: z.string().optional(),
  user: User$inboundSchema.optional(),
  expiresAt: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
});

export function authResponseFromJSON(
  jsonString: string,
): SafeParseResult<AuthResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthResponse' from JSON`,
  );
}
