/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DbQueryResult = {
  count?: number | undefined;
  results?: Array<{ [k: string]: any }> | undefined;
};

/** @internal */
export const DbQueryResult$inboundSchema: z.ZodType<
  DbQueryResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  count: z.number().int().optional(),
  results: z.array(z.record(z.any())).optional(),
});

export function dbQueryResultFromJSON(
  jsonString: string,
): SafeParseResult<DbQueryResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DbQueryResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DbQueryResult' from JSON`,
  );
}
