/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const Code = {
  AuthInvalidKey: "AUTH_INVALID_KEY",
  AuthInvalidCredentials: "AUTH_INVALID_CREDENTIALS",
  DbQueryFailed: "DB_QUERY_FAILED",
  RateLimitExceeded: "RATE_LIMIT_EXCEEDED",
  ValidationError: "VALIDATION_ERROR",
  InternalError: "INTERNAL_ERROR",
} as const;
export type Code = ClosedEnum<typeof Code>;

/**
 * Invalid request
 */
export type ErrorResponse = {
  code: Code;
  message: string;
  details?: { [k: string]: any } | undefined;
};

/** @internal */
export const Code$inboundSchema: z.ZodNativeEnum<typeof Code> = z.nativeEnum(
  Code,
);

/** @internal */
export const ErrorResponse$inboundSchema: z.ZodType<
  ErrorResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: Code$inboundSchema,
  message: z.string(),
  details: z.record(z.any()).optional(),
});

export function errorResponseFromJSON(
  jsonString: string,
): SafeParseResult<ErrorResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorResponse' from JSON`,
  );
}
