/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type TypeStats = {
  type?: string | undefined;
  count?: number | undefined;
};

/** @internal */
export const TypeStats$inboundSchema: z.ZodType<
  TypeStats,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.string().optional(),
  count: z.number().int().optional(),
});

export function typeStatsFromJSON(
  jsonString: string,
): SafeParseResult<TypeStats, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TypeStats$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TypeStats' from JSON`,
  );
}
