/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type User = {
  createdAt?: Date | undefined;
  email?: string | undefined;
  id?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
  name?: string | null | undefined;
};

/** @internal */
export const User$inboundSchema: z.ZodType<User, z.ZodTypeDef, unknown> = z
  .object({
    createdAt: z.string().datetime({ offset: true }).transform(v => new Date(v))
      .optional(),
    email: z.string().optional(),
    id: z.string().optional(),
    metadata: z.record(z.any()).optional(),
    name: z.nullable(z.string()).optional(),
  });

export function userFromJSON(
  jsonString: string,
): SafeParseResult<User, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => User$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'User' from JSON`,
  );
}
