/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const Role = {
  System: "system",
  User: "user",
  Assistant: "assistant",
} as const;
export type Role = ClosedEnum<typeof Role>;

export type Messages = {
  role?: Role | undefined;
  content?: string | undefined;
};

export type AiChatRequestBody = {
  model?: string | undefined;
  messages: Array<Messages>;
};

/**
 * AI response generated
 */
export type AiChatResponseBody = {
  response?: string | undefined;
};

/** @internal */
export const Role$outboundSchema: z.ZodNativeEnum<typeof Role> = z.nativeEnum(
  Role,
);

/** @internal */
export type Messages$Outbound = {
  role?: string | undefined;
  content?: string | undefined;
};

/** @internal */
export const Messages$outboundSchema: z.ZodType<
  Messages$Outbound,
  z.ZodTypeDef,
  Messages
> = z.object({
  role: Role$outboundSchema.optional(),
  content: z.string().optional(),
});

export function messagesToJSON(messages: Messages): string {
  return JSON.stringify(Messages$outboundSchema.parse(messages));
}

/** @internal */
export type AiChatRequestBody$Outbound = {
  model?: string | undefined;
  messages: Array<Messages$Outbound>;
};

/** @internal */
export const AiChatRequestBody$outboundSchema: z.ZodType<
  AiChatRequestBody$Outbound,
  z.ZodTypeDef,
  AiChatRequestBody
> = z.object({
  model: z.string().optional(),
  messages: z.array(z.lazy(() => Messages$outboundSchema)),
});

export function aiChatRequestBodyToJSON(
  aiChatRequestBody: AiChatRequestBody,
): string {
  return JSON.stringify(
    AiChatRequestBody$outboundSchema.parse(aiChatRequestBody),
  );
}

/** @internal */
export const AiChatResponseBody$inboundSchema: z.ZodType<
  AiChatResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  response: z.string().optional(),
});

export function aiChatResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<AiChatResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AiChatResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AiChatResponseBody' from JSON`,
  );
}
