/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type AuthSignupRequestBody = {
  email: string;
  password: string;
  name?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
};

export type AuthSignupResponse = shared.ErrorResponse | shared.AuthResponse;

/** @internal */
export type AuthSignupRequestBody$Outbound = {
  email: string;
  password: string;
  name?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
};

/** @internal */
export const AuthSignupRequestBody$outboundSchema: z.ZodType<
  AuthSignupRequestBody$Outbound,
  z.ZodTypeDef,
  AuthSignupRequestBody
> = z.object({
  email: z.string(),
  password: z.string(),
  name: z.string().optional(),
  metadata: z.record(z.any()).optional(),
});

export function authSignupRequestBodyToJSON(
  authSignupRequestBody: AuthSignupRequestBody,
): string {
  return JSON.stringify(
    AuthSignupRequestBody$outboundSchema.parse(authSignupRequestBody),
  );
}

/** @internal */
export const AuthSignupResponse$inboundSchema: z.ZodType<
  AuthSignupResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.ErrorResponse$inboundSchema,
  shared.AuthResponse$inboundSchema,
]);

export function authSignupResponseFromJSON(
  jsonString: string,
): SafeParseResult<AuthSignupResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthSignupResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthSignupResponse' from JSON`,
  );
}
