/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type AuthSigninRequestBody = {
  email: string;
  password: string;
};

export type AuthSigninResponse = shared.ErrorResponse | shared.AuthResponse;

/** @internal */
export type AuthSigninRequestBody$Outbound = {
  email: string;
  password: string;
};

/** @internal */
export const AuthSigninRequestBody$outboundSchema: z.ZodType<
  AuthSigninRequestBody$Outbound,
  z.ZodTypeDef,
  AuthSigninRequestBody
> = z.object({
  email: z.string(),
  password: z.string(),
});

export function authSigninRequestBodyToJSON(
  authSigninRequestBody: AuthSigninRequestBody,
): string {
  return JSON.stringify(
    AuthSigninRequestBody$outboundSchema.parse(authSigninRequestBody),
  );
}

/** @internal */
export const AuthSigninResponse$inboundSchema: z.ZodType<
  AuthSigninResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.ErrorResponse$inboundSchema,
  shared.AuthResponse$inboundSchema,
]);

export function authSigninResponseFromJSON(
  jsonString: string,
): SafeParseResult<AuthSigninResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthSigninResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthSigninResponse' from JSON`,
  );
}
