/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CacheSetRequestBody = {
  key: string;
  /**
   * Time to live in seconds
   */
  ttl?: number | undefined;
  value?: any | undefined;
};

/**
 * Value cached successfully
 */
export type CacheSetResponseBody = {
  success?: boolean | undefined;
};

/** @internal */
export type CacheSetRequestBody$Outbound = {
  key: string;
  ttl?: number | undefined;
  value?: any | undefined;
};

/** @internal */
export const CacheSetRequestBody$outboundSchema: z.ZodType<
  CacheSetRequestBody$Outbound,
  z.ZodTypeDef,
  CacheSetRequestBody
> = z.object({
  key: z.string(),
  ttl: z.number().int().optional(),
  value: z.any().optional(),
});

export function cacheSetRequestBodyToJSON(
  cacheSetRequestBody: CacheSetRequestBody,
): string {
  return JSON.stringify(
    CacheSetRequestBody$outboundSchema.parse(cacheSetRequestBody),
  );
}

/** @internal */
export const CacheSetResponseBody$inboundSchema: z.ZodType<
  CacheSetResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
});

export function cacheSetResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CacheSetResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CacheSetResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CacheSetResponseBody' from JSON`,
  );
}
