/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CacheGetRequestBody = {
  key: string;
};

/**
 * Cache value retrieved
 */
export type CacheGetResponseBody = {
  value?: any | null | undefined;
  exists?: boolean | undefined;
};

/** @internal */
export type CacheGetRequestBody$Outbound = {
  key: string;
};

/** @internal */
export const CacheGetRequestBody$outboundSchema: z.ZodType<
  CacheGetRequestBody$Outbound,
  z.ZodTypeDef,
  CacheGetRequestBody
> = z.object({
  key: z.string(),
});

export function cacheGetRequestBodyToJSON(
  cacheGetRequestBody: CacheGetRequestBody,
): string {
  return JSON.stringify(
    CacheGetRequestBody$outboundSchema.parse(cacheGetRequestBody),
  );
}

/** @internal */
export const CacheGetResponseBody$inboundSchema: z.ZodType<
  CacheGetResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  value: z.nullable(z.any()).optional(),
  exists: z.boolean().optional(),
});

export function cacheGetResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CacheGetResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CacheGetResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CacheGetResponseBody' from JSON`,
  );
}
