/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const EmbeddingModel = {
  English: "english",
  Multilingual: "multilingual",
} as const;
export type EmbeddingModel = ClosedEnum<typeof EmbeddingModel>;

export type ConfigureRequestBody = {
  embeddingModel: EmbeddingModel;
};

/**
 * Configured
 */
export type ConfigureResponseBody = {
  success?: boolean | undefined;
};

/** @internal */
export const EmbeddingModel$outboundSchema: z.ZodNativeEnum<
  typeof EmbeddingModel
> = z.nativeEnum(EmbeddingModel);

/** @internal */
export type ConfigureRequestBody$Outbound = {
  embeddingModel: string;
};

/** @internal */
export const ConfigureRequestBody$outboundSchema: z.ZodType<
  ConfigureRequestBody$Outbound,
  z.ZodTypeDef,
  ConfigureRequestBody
> = z.object({
  embeddingModel: EmbeddingModel$outboundSchema,
});

export function configureRequestBodyToJSON(
  configureRequestBody: ConfigureRequestBody,
): string {
  return JSON.stringify(
    ConfigureRequestBody$outboundSchema.parse(configureRequestBody),
  );
}

/** @internal */
export const ConfigureResponseBody$inboundSchema: z.ZodType<
  ConfigureResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
});

export function configureResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ConfigureResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConfigureResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConfigureResponseBody' from JSON`,
  );
}
