/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type DbQueryRequestBody = {
  /**
   * SQL query to execute
   */
  sql: string;
  /**
   * Query parameters for prepared statements
   */
  params?: Array<any> | undefined;
};

export type DbQueryRequest = {
  /**
   * Unique request tracing ID
   */
  xRequestID?: string | undefined;
  /**
   * SDK version string
   */
  xSDKVersion?: string | undefined;
  requestBody: DbQueryRequestBody;
};

export type DbQueryResponse = shared.ErrorResponse | shared.DbQueryResult;

/** @internal */
export type DbQueryRequestBody$Outbound = {
  sql: string;
  params?: Array<any> | undefined;
};

/** @internal */
export const DbQueryRequestBody$outboundSchema: z.ZodType<
  DbQueryRequestBody$Outbound,
  z.ZodTypeDef,
  DbQueryRequestBody
> = z.object({
  sql: z.string(),
  params: z.array(z.any()).optional(),
});

export function dbQueryRequestBodyToJSON(
  dbQueryRequestBody: DbQueryRequestBody,
): string {
  return JSON.stringify(
    DbQueryRequestBody$outboundSchema.parse(dbQueryRequestBody),
  );
}

/** @internal */
export type DbQueryRequest$Outbound = {
  "X-Request-ID"?: string | undefined;
  "X-SDK-Version"?: string | undefined;
  RequestBody: DbQueryRequestBody$Outbound;
};

/** @internal */
export const DbQueryRequest$outboundSchema: z.ZodType<
  DbQueryRequest$Outbound,
  z.ZodTypeDef,
  DbQueryRequest
> = z.object({
  xRequestID: z.string().optional(),
  xSDKVersion: z.string().optional(),
  requestBody: z.lazy(() => DbQueryRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    xRequestID: "X-Request-ID",
    xSDKVersion: "X-SDK-Version",
    requestBody: "RequestBody",
  });
});

export function dbQueryRequestToJSON(dbQueryRequest: DbQueryRequest): string {
  return JSON.stringify(DbQueryRequest$outboundSchema.parse(dbQueryRequest));
}

/** @internal */
export const DbQueryResponse$inboundSchema: z.ZodType<
  DbQueryResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.ErrorResponse$inboundSchema,
  shared.DbQueryResult$inboundSchema,
]);

export function dbQueryResponseFromJSON(
  jsonString: string,
): SafeParseResult<DbQueryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DbQueryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DbQueryResponse' from JSON`,
  );
}
