/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type DbQueryRequestBody = {
  /**
   * Query parameters for prepared statements
   */
  params?: Array<any> | undefined;
  /**
   * SQL query to execute
   */
  sql: string;
};

export type DbQueryResponse = shared.ErrorResponse | shared.DbQueryResult;

/** @internal */
export type DbQueryRequestBody$Outbound = {
  params?: Array<any> | undefined;
  sql: string;
};

/** @internal */
export const DbQueryRequestBody$outboundSchema: z.ZodType<
  DbQueryRequestBody$Outbound,
  z.ZodTypeDef,
  DbQueryRequestBody
> = z.object({
  params: z.array(z.any()).optional(),
  sql: z.string(),
});

export function dbQueryRequestBodyToJSON(
  dbQueryRequestBody: DbQueryRequestBody,
): string {
  return JSON.stringify(
    DbQueryRequestBody$outboundSchema.parse(dbQueryRequestBody),
  );
}

/** @internal */
export const DbQueryResponse$inboundSchema: z.ZodType<
  DbQueryResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.ErrorResponse$inboundSchema,
  shared.DbQueryResult$inboundSchema,
]);

export function dbQueryResponseFromJSON(
  jsonString: string,
): SafeParseResult<DbQueryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DbQueryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DbQueryResponse' from JSON`,
  );
}
