/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteByTypeRequestBody = {
  type: string;
};

/**
 * Deleted
 */
export type DeleteByTypeResponseBody = {
  success?: boolean | undefined;
};

/** @internal */
export type DeleteByTypeRequestBody$Outbound = {
  type: string;
};

/** @internal */
export const DeleteByTypeRequestBody$outboundSchema: z.ZodType<
  DeleteByTypeRequestBody$Outbound,
  z.ZodTypeDef,
  DeleteByTypeRequestBody
> = z.object({
  type: z.string(),
});

export function deleteByTypeRequestBodyToJSON(
  deleteByTypeRequestBody: DeleteByTypeRequestBody,
): string {
  return JSON.stringify(
    DeleteByTypeRequestBody$outboundSchema.parse(deleteByTypeRequestBody),
  );
}

/** @internal */
export const DeleteByTypeResponseBody$inboundSchema: z.ZodType<
  DeleteByTypeResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
});

export function deleteByTypeResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<DeleteByTypeResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteByTypeResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteByTypeResponseBody' from JSON`,
  );
}
