/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteRequestBody = {
  id: string;
};

/**
 * Deleted
 */
export type DeleteResponseBody = {
  success?: boolean | undefined;
};

/** @internal */
export type DeleteRequestBody$Outbound = {
  id: string;
};

/** @internal */
export const DeleteRequestBody$outboundSchema: z.ZodType<
  DeleteRequestBody$Outbound,
  z.ZodTypeDef,
  DeleteRequestBody
> = z.object({
  id: z.string(),
});

export function deleteRequestBodyToJSON(
  deleteRequestBody: DeleteRequestBody,
): string {
  return JSON.stringify(
    DeleteRequestBody$outboundSchema.parse(deleteRequestBody),
  );
}

/** @internal */
export const DeleteResponseBody$inboundSchema: z.ZodType<
  DeleteResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
});

export function deleteResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<DeleteResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteResponseBody' from JSON`,
  );
}
