/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type GatewayBillingLogRequestBody = {
  /**
   * The Consumer ID making the request
   */
  consumerId: string;
  /**
   * The Developer Gateway API ID being consumed
   */
  apiId: string;
  /**
   * Optional metric name (default: 'units')
   */
  metric?: string | undefined;
  /**
   * Amount of usage to log
   */
  units: number;
};

/**
 * Usage logged successfully
 */
export type GatewayBillingLogResponseBody = {
  success?: boolean | undefined;
  loggedUnits?: number | undefined;
};

export type GatewayBillingLogResponse =
  | shared.ErrorResponse
  | GatewayBillingLogResponseBody;

/** @internal */
export type GatewayBillingLogRequestBody$Outbound = {
  consumerId: string;
  apiId: string;
  metric?: string | undefined;
  units: number;
};

/** @internal */
export const GatewayBillingLogRequestBody$outboundSchema: z.ZodType<
  GatewayBillingLogRequestBody$Outbound,
  z.ZodTypeDef,
  GatewayBillingLogRequestBody
> = z.object({
  consumerId: z.string(),
  apiId: z.string(),
  metric: z.string().optional(),
  units: z.number().int(),
});

export function gatewayBillingLogRequestBodyToJSON(
  gatewayBillingLogRequestBody: GatewayBillingLogRequestBody,
): string {
  return JSON.stringify(
    GatewayBillingLogRequestBody$outboundSchema.parse(
      gatewayBillingLogRequestBody,
    ),
  );
}

/** @internal */
export const GatewayBillingLogResponseBody$inboundSchema: z.ZodType<
  GatewayBillingLogResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  loggedUnits: z.number().int().optional(),
});

export function gatewayBillingLogResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GatewayBillingLogResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GatewayBillingLogResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GatewayBillingLogResponseBody' from JSON`,
  );
}

/** @internal */
export const GatewayBillingLogResponse$inboundSchema: z.ZodType<
  GatewayBillingLogResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.ErrorResponse$inboundSchema,
  z.lazy(() => GatewayBillingLogResponseBody$inboundSchema),
]);

export function gatewayBillingLogResponseFromJSON(
  jsonString: string,
): SafeParseResult<GatewayBillingLogResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GatewayBillingLogResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GatewayBillingLogResponse' from JSON`,
  );
}
