/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type IngestRequestBody = {
  /**
   * Text content to index
   */
  content: string;
  /**
   * Optional custom ID
   */
  id?: string | undefined;
  /**
   * Category/type of content
   */
  type: string;
  metadata?: { [k: string]: any } | undefined;
};

/**
 * Content ingested successfully
 */
export type IngestResponseBody = {
  success?: boolean | undefined;
};

/** @internal */
export type IngestRequestBody$Outbound = {
  content: string;
  id?: string | undefined;
  type: string;
  metadata?: { [k: string]: any } | undefined;
};

/** @internal */
export const IngestRequestBody$outboundSchema: z.ZodType<
  IngestRequestBody$Outbound,
  z.ZodTypeDef,
  IngestRequestBody
> = z.object({
  content: z.string(),
  id: z.string().optional(),
  type: z.string(),
  metadata: z.record(z.any()).optional(),
});

export function ingestRequestBodyToJSON(
  ingestRequestBody: IngestRequestBody,
): string {
  return JSON.stringify(
    IngestRequestBody$outboundSchema.parse(ingestRequestBody),
  );
}

/** @internal */
export const IngestResponseBody$inboundSchema: z.ZodType<
  IngestResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
});

export function ingestResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<IngestResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IngestResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IngestResponseBody' from JSON`,
  );
}
