/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

/**
 * Type statistics
 */
export type ListTypesResponseBody = {
  types?: Array<shared.TypeStats> | undefined;
};

/** @internal */
export const ListTypesResponseBody$inboundSchema: z.ZodType<
  ListTypesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  types: z.array(shared.TypeStats$inboundSchema).optional(),
});

export function listTypesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListTypesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListTypesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListTypesResponseBody' from JSON`,
  );
}
