/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type QueryRequestBody = {
  text: string;
  topK?: number | undefined;
  types?: Array<string> | undefined;
  filter?: { [k: string]: any } | undefined;
};

/**
 * Search results
 */
export type QueryResponseBody = {
  results?: Array<shared.SearchResult> | undefined;
};

/** @internal */
export type QueryRequestBody$Outbound = {
  text: string;
  topK: number;
  types?: Array<string> | undefined;
  filter?: { [k: string]: any } | undefined;
};

/** @internal */
export const QueryRequestBody$outboundSchema: z.ZodType<
  QueryRequestBody$Outbound,
  z.ZodTypeDef,
  QueryRequestBody
> = z.object({
  text: z.string(),
  topK: z.number().int().default(5),
  types: z.array(z.string()).optional(),
  filter: z.record(z.any()).optional(),
});

export function queryRequestBodyToJSON(
  queryRequestBody: QueryRequestBody,
): string {
  return JSON.stringify(
    QueryRequestBody$outboundSchema.parse(queryRequestBody),
  );
}

/** @internal */
export const QueryResponseBody$inboundSchema: z.ZodType<
  QueryResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  results: z.array(shared.SearchResult$inboundSchema).optional(),
});

export function queryResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<QueryResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryResponseBody' from JSON`,
  );
}
