/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type QueueEnqueueRequestBody = {
  data: { [k: string]: any };
  /**
   * Delay in seconds before processing
   */
  delay?: number | undefined;
  type: string;
};

/**
 * Job enqueued successfully
 */
export type QueueEnqueueResponseBody = {
  jobId?: string | undefined;
  success?: boolean | undefined;
};

/** @internal */
export type QueueEnqueueRequestBody$Outbound = {
  data: { [k: string]: any };
  delay?: number | undefined;
  type: string;
};

/** @internal */
export const QueueEnqueueRequestBody$outboundSchema: z.ZodType<
  QueueEnqueueRequestBody$Outbound,
  z.ZodTypeDef,
  QueueEnqueueRequestBody
> = z.object({
  data: z.record(z.any()),
  delay: z.number().int().optional(),
  type: z.string(),
});

export function queueEnqueueRequestBodyToJSON(
  queueEnqueueRequestBody: QueueEnqueueRequestBody,
): string {
  return JSON.stringify(
    QueueEnqueueRequestBody$outboundSchema.parse(queueEnqueueRequestBody),
  );
}

/** @internal */
export const QueueEnqueueResponseBody$inboundSchema: z.ZodType<
  QueueEnqueueResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  jobId: z.string().optional(),
  success: z.boolean().optional(),
});

export function queueEnqueueResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<QueueEnqueueResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueueEnqueueResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueueEnqueueResponseBody' from JSON`,
  );
}
