/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ServicesInvokeRequestBody = {
  serviceName: string;
  data: { [k: string]: any };
};

/**
 * Service invoked successfully
 */
export type ServicesInvokeResponseBody = {
  success?: boolean | undefined;
  result?: any | undefined;
};

/** @internal */
export type ServicesInvokeRequestBody$Outbound = {
  serviceName: string;
  data: { [k: string]: any };
};

/** @internal */
export const ServicesInvokeRequestBody$outboundSchema: z.ZodType<
  ServicesInvokeRequestBody$Outbound,
  z.ZodTypeDef,
  ServicesInvokeRequestBody
> = z.object({
  serviceName: z.string(),
  data: z.record(z.any()),
});

export function servicesInvokeRequestBodyToJSON(
  servicesInvokeRequestBody: ServicesInvokeRequestBody,
): string {
  return JSON.stringify(
    ServicesInvokeRequestBody$outboundSchema.parse(servicesInvokeRequestBody),
  );
}

/** @internal */
export const ServicesInvokeResponseBody$inboundSchema: z.ZodType<
  ServicesInvokeResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  result: z.any().optional(),
});

export function servicesInvokeResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ServicesInvokeResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ServicesInvokeResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ServicesInvokeResponseBody' from JSON`,
  );
}
