/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { blobLikeSchema } from "../../types/blobs.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type FileT = {
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
  fileName: string;
};

export type StorageUploadRequestBody = {
  contentType?: string | undefined;
  file: FileT | Blob;
  /**
   * Storage key/path
   */
  key: string;
};

/**
 * File uploaded successfully
 */
export type StorageUploadResponseBody = {
  url?: string | undefined;
};

/** @internal */
export type FileT$Outbound = {
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
  fileName: string;
};

/** @internal */
export const FileT$outboundSchema: z.ZodType<
  FileT$Outbound,
  z.ZodTypeDef,
  FileT
> = z.object({
  content: z.union([
    z.instanceof(ReadableStream<Uint8Array>),
    z.instanceof(Blob),
    z.instanceof(ArrayBuffer),
    z.instanceof(Uint8Array),
  ]),
  fileName: z.string(),
});

export function fileToJSON(fileT: FileT): string {
  return JSON.stringify(FileT$outboundSchema.parse(fileT));
}

/** @internal */
export type StorageUploadRequestBody$Outbound = {
  contentType?: string | undefined;
  file: FileT$Outbound | Blob;
  key: string;
};

/** @internal */
export const StorageUploadRequestBody$outboundSchema: z.ZodType<
  StorageUploadRequestBody$Outbound,
  z.ZodTypeDef,
  StorageUploadRequestBody
> = z.object({
  contentType: z.string().optional(),
  file: z.lazy(() => FileT$outboundSchema).or(blobLikeSchema),
  key: z.string(),
});

export function storageUploadRequestBodyToJSON(
  storageUploadRequestBody: StorageUploadRequestBody,
): string {
  return JSON.stringify(
    StorageUploadRequestBody$outboundSchema.parse(storageUploadRequestBody),
  );
}

/** @internal */
export const StorageUploadResponseBody$inboundSchema: z.ZodType<
  StorageUploadResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  url: z.string().optional(),
});

export function storageUploadResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<StorageUploadResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StorageUploadResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StorageUploadResponseBody' from JSON`,
  );
}
