/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { aiAIChat } from "../funcs/aiAIChat.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Ai extends ClientSDK {
  /**
   * Generate AI chat completion
   */
  async aiChat(
    request: operations.AiChatRequestBody,
    options?: RequestOptions,
  ): Promise<operations.AiChatResponseBody> {
    return unwrapAsync(aiAIChat(
      this,
      request,
      options,
    ));
  }
}
