/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authenticationAuthSignin } from "../funcs/authenticationAuthSignin.js";
import { authenticationAuthSignup } from "../funcs/authenticationAuthSignup.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Authentication extends ClientSDK {
  /**
   * Sign in user
   */
  async authSignin(
    request: operations.AuthSigninRequestBody,
    options?: RequestOptions,
  ): Promise<operations.AuthSigninResponse> {
    return unwrapAsync(authenticationAuthSignin(
      this,
      request,
      options,
    ));
  }

  /**
   * Sign up new user
   */
  async authSignup(
    request: operations.AuthSignupRequestBody,
    options?: RequestOptions,
  ): Promise<operations.AuthSignupResponse> {
    return unwrapAsync(authenticationAuthSignup(
      this,
      request,
      options,
    ));
  }
}
