/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { gatewayBillingGatewayBillingLog } from "../funcs/gatewayBillingGatewayBillingLog.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Billing extends ClientSDK {
  /**
   * Log Gateway usage
   *
   * @remarks
   * Manually log tokens or custom metric usage for a Gateway API
   */
  async gatewayBillingLog(
    request: operations.GatewayBillingLogRequestBody,
    options?: RequestOptions,
  ): Promise<operations.GatewayBillingLogResponse> {
    return unwrapAsync(gatewayBillingGatewayBillingLog(
      this,
      request,
      options,
    ));
  }
}
