/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { cacheCacheGet } from "../funcs/cacheCacheGet.js";
import { cacheCacheSet } from "../funcs/cacheCacheSet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Cache extends ClientSDK {
  /**
   * Get cached value
   */
  async cacheGet(
    request: operations.CacheGetRequestBody,
    options?: RequestOptions,
  ): Promise<operations.CacheGetResponseBody> {
    return unwrapAsync(cacheCacheGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Set cached value
   */
  async cacheSet(
    request: operations.CacheSetRequestBody,
    options?: RequestOptions,
  ): Promise<operations.CacheSetResponseBody> {
    return unwrapAsync(cacheCacheSet(
      this,
      request,
      options,
    ));
  }
}
