/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { databaseDbQuery } from "../funcs/databaseDbQuery.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Database extends ClientSDK {
  /**
   * Execute SQL query
   *
   * @remarks
   * Run a SQL query against your project database
   */
  async dbQuery(
    request: operations.DbQueryRequestBody,
    options?: RequestOptions,
  ): Promise<operations.DbQueryResponse> {
    return unwrapAsync(databaseDbQuery(
      this,
      request,
      options,
    ));
  }
}
