/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Billing } from "./billing.js";

export class Gateway extends ClientSDK {
  private _billing?: Billing;
  get billing(): Billing {
    return (this._billing ??= new Billing(this._options));
  }
}
