/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { queueQueueEnqueue } from "../funcs/queueQueueEnqueue.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Queue extends ClientSDK {
  /**
   * Add job to queue
   */
  async queueEnqueue(
    request: operations.QueueEnqueueRequestBody,
    options?: RequestOptions,
  ): Promise<operations.QueueEnqueueResponseBody> {
    return unwrapAsync(queueQueueEnqueue(
      this,
      request,
      options,
    ));
  }
}
