/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Ai } from "./ai.js";
import { Authentication } from "./authentication.js";
import { Cache } from "./cache.js";
import { Database } from "./database.js";
import { Gateway } from "./gateway.js";
import { Queue } from "./queue.js";
import { Services } from "./services.js";
import { Storage } from "./storage.js";

export class SDK extends ClientSDK {
  private _database?: Database;
  get database(): Database {
    return (this._database ??= new Database(this._options));
  }

  private _authentication?: Authentication;
  get authentication(): Authentication {
    return (this._authentication ??= new Authentication(this._options));
  }

  private _cache?: Cache;
  get cache(): Cache {
    return (this._cache ??= new Cache(this._options));
  }

  private _queue?: Queue;
  get queue(): Queue {
    return (this._queue ??= new Queue(this._options));
  }

  private _storage?: Storage;
  get storage(): Storage {
    return (this._storage ??= new Storage(this._options));
  }

  private _ai?: Ai;
  get ai(): Ai {
    return (this._ai ??= new Ai(this._options));
  }

  private _services?: Services;
  get services(): Services {
    return (this._services ??= new Services(this._options));
  }

  private _gateway?: Gateway;
  get gateway(): Gateway {
    return (this._gateway ??= new Gateway(this._options));
  }
}
