/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { aiSearchConfigure } from "../funcs/aiSearchConfigure.js";
import { aiSearchDelete } from "../funcs/aiSearchDelete.js";
import { aiSearchDeleteByType } from "../funcs/aiSearchDeleteByType.js";
import { aiSearchIngest } from "../funcs/aiSearchIngest.js";
import { aiSearchListTypes } from "../funcs/aiSearchListTypes.js";
import { aiSearchQuery } from "../funcs/aiSearchQuery.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Search extends ClientSDK {
  /**
   * Ingest content into managed search index
   */
  async ingest(
    request: operations.IngestRequestBody,
    options?: RequestOptions,
  ): Promise<operations.IngestResponseBody> {
    return unwrapAsync(aiSearchIngest(
      this,
      request,
      options,
    ));
  }

  /**
   * Search managed index
   */
  async query(
    request: operations.QueryRequestBody,
    options?: RequestOptions,
  ): Promise<operations.QueryResponseBody> {
    return unwrapAsync(aiSearchQuery(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete item by ID
   */
  async delete(
    request: operations.DeleteRequestBody,
    options?: RequestOptions,
  ): Promise<operations.DeleteResponseBody> {
    return unwrapAsync(aiSearchDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete all items of a type
   */
  async deleteByType(
    request: operations.DeleteByTypeRequestBody,
    options?: RequestOptions,
  ): Promise<operations.DeleteByTypeResponseBody> {
    return unwrapAsync(aiSearchDeleteByType(
      this,
      request,
      options,
    ));
  }

  /**
   * List distinct types and counts
   */
  async listTypes(
    options?: RequestOptions,
  ): Promise<operations.ListTypesResponseBody> {
    return unwrapAsync(aiSearchListTypes(
      this,
      options,
    ));
  }

  /**
   * Update search configuration
   */
  async configure(
    request: operations.ConfigureRequestBody,
    options?: RequestOptions,
  ): Promise<operations.ConfigureResponseBody> {
    return unwrapAsync(aiSearchConfigure(
      this,
      request,
      options,
    ));
  }
}
