/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { servicesServicesInvoke } from "../funcs/servicesServicesInvoke.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Services extends ClientSDK {
  /**
   * Invoke another service
   */
  async servicesInvoke(
    request: operations.ServicesInvokeRequestBody,
    options?: RequestOptions,
  ): Promise<operations.ServicesInvokeResponseBody> {
    return unwrapAsync(servicesServicesInvoke(
      this,
      request,
      options,
    ));
  }
}
