/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { storageStorageUpload } from "../funcs/storageStorageUpload.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Storage extends ClientSDK {
  /**
   * Upload file to storage
   */
  async storageUpload(
    request: operations.StorageUploadRequestBody,
    options?: RequestOptions,
  ): Promise<operations.StorageUploadResponseBody> {
    return unwrapAsync(storageStorageUpload(
      this,
      request,
      options,
    ));
  }
}
