/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @aerostack/sdk-web SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx databaseDbQuery.example.ts
 */

import { SDK } from "@aerostack/sdk-web";

const sdk = new SDK({
  apiKeyAuth: "<YOUR_API_KEY_HERE>",
});

async function main() {
  const result = await sdk.database.dbQuery({
    sql: "SELECT * FROM users WHERE active = ?",
    params: [
      true,
    ],
  });

  console.log(result);
}

main().catch(console.error);
