/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  CacheSet200Response,
  ChatCompletionRequest,
  ChatCompletionResponse,
  ConfigureRequest,
  DeleteByTypeRequest,
  DeleteRequest,
  IngestRequest,
  ListTypes200Response,
  Query200Response,
  QueryRequest,
  SearchCount200Response,
  SearchCountRequest,
  SearchGet200Response,
  SearchGetRequest,
  SearchUpdateRequest,
} from '../models/index.js';
import {
    CacheSet200ResponseFromJSON,
    CacheSet200ResponseToJSON,
    ChatCompletionRequestFromJSON,
    ChatCompletionRequestToJSON,
    ChatCompletionResponseFromJSON,
    ChatCompletionResponseToJSON,
    ConfigureRequestFromJSON,
    ConfigureRequestToJSON,
    DeleteByTypeRequestFromJSON,
    DeleteByTypeRequestToJSON,
    DeleteRequestFromJSON,
    DeleteRequestToJSON,
    IngestRequestFromJSON,
    IngestRequestToJSON,
    ListTypes200ResponseFromJSON,
    ListTypes200ResponseToJSON,
    Query200ResponseFromJSON,
    Query200ResponseToJSON,
    QueryRequestFromJSON,
    QueryRequestToJSON,
    SearchCount200ResponseFromJSON,
    SearchCount200ResponseToJSON,
    SearchCountRequestFromJSON,
    SearchCountRequestToJSON,
    SearchGet200ResponseFromJSON,
    SearchGet200ResponseToJSON,
    SearchGetRequestFromJSON,
    SearchGetRequestToJSON,
    SearchUpdateRequestFromJSON,
    SearchUpdateRequestToJSON,
} from '../models/index.js';

export interface DeleteOperationRequest {
    deleteRequest: DeleteRequest;
}

export interface AiChatRequest {
    chatCompletionRequest: ChatCompletionRequest;
}

export interface ConfigureOperationRequest {
    configureRequest: ConfigureRequest;
}

export interface DeleteByTypeOperationRequest {
    deleteByTypeRequest: DeleteByTypeRequest;
}

export interface IngestOperationRequest {
    ingestRequest: IngestRequest;
}

export interface QueryOperationRequest {
    queryRequest: QueryRequest;
}

export interface SearchCountOperationRequest {
    searchCountRequest: SearchCountRequest;
}

export interface SearchGetOperationRequest {
    searchGetRequest: SearchGetRequest;
}

export interface SearchUpdateOperationRequest {
    searchUpdateRequest: SearchUpdateRequest;
}

/**
 * 
 */
export class AIApi extends runtime.BaseAPI {

    /**
     * Delete item by ID
     */
    async _deleteRaw(requestParameters: DeleteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CacheSet200Response>> {
        if (requestParameters.deleteRequest === null || requestParameters.deleteRequest === undefined) {
            throw new runtime.RequiredError('deleteRequest','Required parameter requestParameters.deleteRequest was null or undefined when calling _delete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/ai/search/delete`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteRequestToJSON(requestParameters.deleteRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CacheSet200ResponseFromJSON(jsonValue));
    }

    /**
     * Delete item by ID
     */
    async _delete(requestParameters: DeleteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CacheSet200Response> {
        const response = await this._deleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generate a chat completion using the project\'s configured AI model. Set `stream: true` to receive a server-sent events (SSE) stream of token deltas in OpenAI-compatible format. Each data frame contains a JSON object with `choices[0].delta.content`. The stream ends with `data: [DONE]`. The final frame (when `stream_options.include_usage` is true) includes a `usage` object with `total_tokens`. 
     * Generate AI chat completion
     */
    async aiChatRaw(requestParameters: AiChatRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChatCompletionResponse>> {
        if (requestParameters.chatCompletionRequest === null || requestParameters.chatCompletionRequest === undefined) {
            throw new runtime.RequiredError('chatCompletionRequest','Required parameter requestParameters.chatCompletionRequest was null or undefined when calling aiChat.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/ai/chat`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChatCompletionRequestToJSON(requestParameters.chatCompletionRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChatCompletionResponseFromJSON(jsonValue));
    }

    /**
     * Generate a chat completion using the project\'s configured AI model. Set `stream: true` to receive a server-sent events (SSE) stream of token deltas in OpenAI-compatible format. Each data frame contains a JSON object with `choices[0].delta.content`. The stream ends with `data: [DONE]`. The final frame (when `stream_options.include_usage` is true) includes a `usage` object with `total_tokens`. 
     * Generate AI chat completion
     */
    async aiChat(requestParameters: AiChatRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChatCompletionResponse> {
        const response = await this.aiChatRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update search configuration
     */
    async configureRaw(requestParameters: ConfigureOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CacheSet200Response>> {
        if (requestParameters.configureRequest === null || requestParameters.configureRequest === undefined) {
            throw new runtime.RequiredError('configureRequest','Required parameter requestParameters.configureRequest was null or undefined when calling configure.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/ai/search/configure`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConfigureRequestToJSON(requestParameters.configureRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CacheSet200ResponseFromJSON(jsonValue));
    }

    /**
     * Update search configuration
     */
    async configure(requestParameters: ConfigureOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CacheSet200Response> {
        const response = await this.configureRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete all items of a type
     */
    async deleteByTypeRaw(requestParameters: DeleteByTypeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CacheSet200Response>> {
        if (requestParameters.deleteByTypeRequest === null || requestParameters.deleteByTypeRequest === undefined) {
            throw new runtime.RequiredError('deleteByTypeRequest','Required parameter requestParameters.deleteByTypeRequest was null or undefined when calling deleteByType.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/ai/search/deleteByType`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteByTypeRequestToJSON(requestParameters.deleteByTypeRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CacheSet200ResponseFromJSON(jsonValue));
    }

    /**
     * Delete all items of a type
     */
    async deleteByType(requestParameters: DeleteByTypeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CacheSet200Response> {
        const response = await this.deleteByTypeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Ingest content into managed search index
     */
    async ingestRaw(requestParameters: IngestOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CacheSet200Response>> {
        if (requestParameters.ingestRequest === null || requestParameters.ingestRequest === undefined) {
            throw new runtime.RequiredError('ingestRequest','Required parameter requestParameters.ingestRequest was null or undefined when calling ingest.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/ai/search/ingest`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IngestRequestToJSON(requestParameters.ingestRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CacheSet200ResponseFromJSON(jsonValue));
    }

    /**
     * Ingest content into managed search index
     */
    async ingest(requestParameters: IngestOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CacheSet200Response> {
        const response = await this.ingestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List distinct types and counts
     */
    async listTypesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListTypes200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/ai/search/listTypes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListTypes200ResponseFromJSON(jsonValue));
    }

    /**
     * List distinct types and counts
     */
    async listTypes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListTypes200Response> {
        const response = await this.listTypesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Search managed index
     */
    async queryRaw(requestParameters: QueryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Query200Response>> {
        if (requestParameters.queryRequest === null || requestParameters.queryRequest === undefined) {
            throw new runtime.RequiredError('queryRequest','Required parameter requestParameters.queryRequest was null or undefined when calling query.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/ai/search/query`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: QueryRequestToJSON(requestParameters.queryRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Query200ResponseFromJSON(jsonValue));
    }

    /**
     * Search managed index
     */
    async query(requestParameters: QueryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Query200Response> {
        const response = await this.queryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns total count of indexed items, optionally filtered by type.
     * Count indexed items
     */
    async searchCountRaw(requestParameters: SearchCountOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchCount200Response>> {
        if (requestParameters.searchCountRequest === null || requestParameters.searchCountRequest === undefined) {
            throw new runtime.RequiredError('searchCountRequest','Required parameter requestParameters.searchCountRequest was null or undefined when calling searchCount.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/ai/search/count`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchCountRequestToJSON(requestParameters.searchCountRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchCount200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns total count of indexed items, optionally filtered by type.
     * Count indexed items
     */
    async searchCount(requestParameters: SearchCountOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchCount200Response> {
        const response = await this.searchCountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a specific indexed item by ID
     */
    async searchGetRaw(requestParameters: SearchGetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchGet200Response>> {
        if (requestParameters.searchGetRequest === null || requestParameters.searchGetRequest === undefined) {
            throw new runtime.RequiredError('searchGetRequest','Required parameter requestParameters.searchGetRequest was null or undefined when calling searchGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/ai/search/get`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchGetRequestToJSON(requestParameters.searchGetRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Get a specific indexed item by ID
     */
    async searchGet(requestParameters: SearchGetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchGet200Response> {
        const response = await this.searchGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates a previously ingested item by re-ingesting with the same ID. The Vectorize upsert operation is idempotent — re-ingesting with the same ID replaces the existing vector and metadata. 
     * Update an existing indexed item
     */
    async searchUpdateRaw(requestParameters: SearchUpdateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CacheSet200Response>> {
        if (requestParameters.searchUpdateRequest === null || requestParameters.searchUpdateRequest === undefined) {
            throw new runtime.RequiredError('searchUpdateRequest','Required parameter requestParameters.searchUpdateRequest was null or undefined when calling searchUpdate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/ai/search/update`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchUpdateRequestToJSON(requestParameters.searchUpdateRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CacheSet200ResponseFromJSON(jsonValue));
    }

    /**
     * Updates a previously ingested item by re-ingesting with the same ID. The Vectorize upsert operation is idempotent — re-ingesting with the same ID replaces the existing vector and metadata. 
     * Update an existing indexed item
     */
    async searchUpdate(requestParameters: SearchUpdateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CacheSet200Response> {
        const response = await this.searchUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
