/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  AiChat200Response,
  AiChatRequest,
  CacheSet200Response,
  ConfigureRequest,
  DeleteByTypeRequest,
  DeleteRequest,
  IngestRequest,
  ListTypes200Response,
  Query200Response,
  QueryRequest,
} from '../models/index.js';
import {
    AiChat200ResponseFromJSON,
    AiChat200ResponseToJSON,
    AiChatRequestFromJSON,
    AiChatRequestToJSON,
    CacheSet200ResponseFromJSON,
    CacheSet200ResponseToJSON,
    ConfigureRequestFromJSON,
    ConfigureRequestToJSON,
    DeleteByTypeRequestFromJSON,
    DeleteByTypeRequestToJSON,
    DeleteRequestFromJSON,
    DeleteRequestToJSON,
    IngestRequestFromJSON,
    IngestRequestToJSON,
    ListTypes200ResponseFromJSON,
    ListTypes200ResponseToJSON,
    Query200ResponseFromJSON,
    Query200ResponseToJSON,
    QueryRequestFromJSON,
    QueryRequestToJSON,
} from '../models/index.js';

export interface DeleteOperationRequest {
    deleteRequest: DeleteRequest;
}

export interface AiChatOperationRequest {
    aiChatRequest: AiChatRequest;
}

export interface ConfigureOperationRequest {
    configureRequest: ConfigureRequest;
}

export interface DeleteByTypeOperationRequest {
    deleteByTypeRequest: DeleteByTypeRequest;
}

export interface IngestOperationRequest {
    ingestRequest: IngestRequest;
}

export interface QueryOperationRequest {
    queryRequest: QueryRequest;
}

/**
 * 
 */
export class AIApi extends runtime.BaseAPI {

    /**
     * Delete item by ID
     */
    async _deleteRaw(requestParameters: DeleteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CacheSet200Response>> {
        if (requestParameters.deleteRequest === null || requestParameters.deleteRequest === undefined) {
            throw new runtime.RequiredError('deleteRequest','Required parameter requestParameters.deleteRequest was null or undefined when calling _delete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/ai/search/delete`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteRequestToJSON(requestParameters.deleteRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CacheSet200ResponseFromJSON(jsonValue));
    }

    /**
     * Delete item by ID
     */
    async _delete(requestParameters: DeleteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CacheSet200Response> {
        const response = await this._deleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generate AI chat completion
     */
    async aiChatRaw(requestParameters: AiChatOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AiChat200Response>> {
        if (requestParameters.aiChatRequest === null || requestParameters.aiChatRequest === undefined) {
            throw new runtime.RequiredError('aiChatRequest','Required parameter requestParameters.aiChatRequest was null or undefined when calling aiChat.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/ai/chat`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AiChatRequestToJSON(requestParameters.aiChatRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AiChat200ResponseFromJSON(jsonValue));
    }

    /**
     * Generate AI chat completion
     */
    async aiChat(requestParameters: AiChatOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AiChat200Response> {
        const response = await this.aiChatRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update search configuration
     */
    async configureRaw(requestParameters: ConfigureOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CacheSet200Response>> {
        if (requestParameters.configureRequest === null || requestParameters.configureRequest === undefined) {
            throw new runtime.RequiredError('configureRequest','Required parameter requestParameters.configureRequest was null or undefined when calling configure.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/ai/search/configure`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConfigureRequestToJSON(requestParameters.configureRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CacheSet200ResponseFromJSON(jsonValue));
    }

    /**
     * Update search configuration
     */
    async configure(requestParameters: ConfigureOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CacheSet200Response> {
        const response = await this.configureRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete all items of a type
     */
    async deleteByTypeRaw(requestParameters: DeleteByTypeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CacheSet200Response>> {
        if (requestParameters.deleteByTypeRequest === null || requestParameters.deleteByTypeRequest === undefined) {
            throw new runtime.RequiredError('deleteByTypeRequest','Required parameter requestParameters.deleteByTypeRequest was null or undefined when calling deleteByType.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/ai/search/deleteByType`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteByTypeRequestToJSON(requestParameters.deleteByTypeRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CacheSet200ResponseFromJSON(jsonValue));
    }

    /**
     * Delete all items of a type
     */
    async deleteByType(requestParameters: DeleteByTypeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CacheSet200Response> {
        const response = await this.deleteByTypeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Ingest content into managed search index
     */
    async ingestRaw(requestParameters: IngestOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CacheSet200Response>> {
        if (requestParameters.ingestRequest === null || requestParameters.ingestRequest === undefined) {
            throw new runtime.RequiredError('ingestRequest','Required parameter requestParameters.ingestRequest was null or undefined when calling ingest.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/ai/search/ingest`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IngestRequestToJSON(requestParameters.ingestRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CacheSet200ResponseFromJSON(jsonValue));
    }

    /**
     * Ingest content into managed search index
     */
    async ingest(requestParameters: IngestOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CacheSet200Response> {
        const response = await this.ingestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List distinct types and counts
     */
    async listTypesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListTypes200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/ai/search/listTypes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListTypes200ResponseFromJSON(jsonValue));
    }

    /**
     * List distinct types and counts
     */
    async listTypes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListTypes200Response> {
        const response = await this.listTypesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Search managed index
     */
    async queryRaw(requestParameters: QueryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Query200Response>> {
        if (requestParameters.queryRequest === null || requestParameters.queryRequest === undefined) {
            throw new runtime.RequiredError('queryRequest','Required parameter requestParameters.queryRequest was null or undefined when calling query.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/ai/search/query`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: QueryRequestToJSON(requestParameters.queryRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Query200ResponseFromJSON(jsonValue));
    }

    /**
     * Search managed index
     */
    async query(requestParameters: QueryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Query200Response> {
        const response = await this.queryRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
