/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  AuthResponse,
  AuthSigninRequest,
  AuthSignupRequest,
  ErrorResponse,
} from '../models/index.js';
import {
    AuthResponseFromJSON,
    AuthResponseToJSON,
    AuthSigninRequestFromJSON,
    AuthSigninRequestToJSON,
    AuthSignupRequestFromJSON,
    AuthSignupRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/index.js';

export interface AuthSigninOperationRequest {
    authSigninRequest: AuthSigninRequest;
}

export interface AuthSignupOperationRequest {
    authSignupRequest: AuthSignupRequest;
}

/**
 * 
 */
export class AuthenticationApi extends runtime.BaseAPI {

    /**
     * Sign in user
     */
    async authSigninRaw(requestParameters: AuthSigninOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthResponse>> {
        if (requestParameters.authSigninRequest === null || requestParameters.authSigninRequest === undefined) {
            throw new runtime.RequiredError('authSigninRequest','Required parameter requestParameters.authSigninRequest was null or undefined when calling authSignin.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/auth/signin`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthSigninRequestToJSON(requestParameters.authSigninRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthResponseFromJSON(jsonValue));
    }

    /**
     * Sign in user
     */
    async authSignin(requestParameters: AuthSigninOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthResponse> {
        const response = await this.authSigninRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Sign up new user
     */
    async authSignupRaw(requestParameters: AuthSignupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthResponse>> {
        if (requestParameters.authSignupRequest === null || requestParameters.authSignupRequest === undefined) {
            throw new runtime.RequiredError('authSignupRequest','Required parameter requestParameters.authSignupRequest was null or undefined when calling authSignup.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/auth/signup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthSignupRequestToJSON(requestParameters.authSignupRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthResponseFromJSON(jsonValue));
    }

    /**
     * Sign up new user
     */
    async authSignup(requestParameters: AuthSignupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthResponse> {
        const response = await this.authSignupRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
