/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  CacheGet200Response,
  CacheGetRequest,
  CacheSet200Response,
  CacheSetRequest,
} from '../models/index.js';
import {
    CacheGet200ResponseFromJSON,
    CacheGet200ResponseToJSON,
    CacheGetRequestFromJSON,
    CacheGetRequestToJSON,
    CacheSet200ResponseFromJSON,
    CacheSet200ResponseToJSON,
    CacheSetRequestFromJSON,
    CacheSetRequestToJSON,
} from '../models/index.js';

export interface CacheGetOperationRequest {
    cacheGetRequest: CacheGetRequest;
}

export interface CacheSetOperationRequest {
    cacheSetRequest: CacheSetRequest;
}

/**
 * 
 */
export class CacheApi extends runtime.BaseAPI {

    /**
     * Get cached value
     */
    async cacheGetRaw(requestParameters: CacheGetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CacheGet200Response>> {
        if (requestParameters.cacheGetRequest === null || requestParameters.cacheGetRequest === undefined) {
            throw new runtime.RequiredError('cacheGetRequest','Required parameter requestParameters.cacheGetRequest was null or undefined when calling cacheGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/cache/get`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CacheGetRequestToJSON(requestParameters.cacheGetRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CacheGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Get cached value
     */
    async cacheGet(requestParameters: CacheGetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CacheGet200Response> {
        const response = await this.cacheGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Set cached value
     */
    async cacheSetRaw(requestParameters: CacheSetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CacheSet200Response>> {
        if (requestParameters.cacheSetRequest === null || requestParameters.cacheSetRequest === undefined) {
            throw new runtime.RequiredError('cacheSetRequest','Required parameter requestParameters.cacheSetRequest was null or undefined when calling cacheSet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/cache/set`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CacheSetRequestToJSON(requestParameters.cacheSetRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CacheSet200ResponseFromJSON(jsonValue));
    }

    /**
     * Set cached value
     */
    async cacheSet(requestParameters: CacheSetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CacheSet200Response> {
        const response = await this.cacheSetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
