/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  DbQueryRequest,
  DbQueryResult,
  ErrorResponse,
} from '../models/index.js';
import {
    DbQueryRequestFromJSON,
    DbQueryRequestToJSON,
    DbQueryResultFromJSON,
    DbQueryResultToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/index.js';

export interface DbQueryOperationRequest {
    dbQueryRequest: DbQueryRequest;
    xRequestID?: string;
    xSDKVersion?: string;
}

/**
 * 
 */
export class DatabaseApi extends runtime.BaseAPI {

    /**
     * Run a SQL query against your project database
     * Execute SQL query
     */
    async dbQueryRaw(requestParameters: DbQueryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DbQueryResult>> {
        if (requestParameters.dbQueryRequest === null || requestParameters.dbQueryRequest === undefined) {
            throw new runtime.RequiredError('dbQueryRequest','Required parameter requestParameters.dbQueryRequest was null or undefined when calling dbQuery.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters.xRequestID !== undefined && requestParameters.xRequestID !== null) {
            headerParameters['X-Request-ID'] = String(requestParameters.xRequestID);
        }

        if (requestParameters.xSDKVersion !== undefined && requestParameters.xSDKVersion !== null) {
            headerParameters['X-SDK-Version'] = String(requestParameters.xSDKVersion);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/db/query`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DbQueryRequestToJSON(requestParameters.dbQueryRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DbQueryResultFromJSON(jsonValue));
    }

    /**
     * Run a SQL query against your project database
     * Execute SQL query
     */
    async dbQuery(requestParameters: DbQueryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DbQueryResult> {
        const response = await this.dbQueryRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
