/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  DbBatchRequest,
  DbBatchResult,
  DbQueryRequest,
  DbQueryResult,
  ErrorResponse,
} from '../models/index.js';
import {
    DbBatchRequestFromJSON,
    DbBatchRequestToJSON,
    DbBatchResultFromJSON,
    DbBatchResultToJSON,
    DbQueryRequestFromJSON,
    DbQueryRequestToJSON,
    DbQueryResultFromJSON,
    DbQueryResultToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/index.js';

export interface DbBatchOperationRequest {
    dbBatchRequest: DbBatchRequest;
}

export interface DbQueryOperationRequest {
    dbQueryRequest: DbQueryRequest;
    xRequestID?: string;
    xSDKVersion?: string;
}

/**
 * 
 */
export class DatabaseApi extends runtime.BaseAPI {

    /**
     * Run up to 25 SQL queries in a single request. Each query runs through the same sanitization and project-isolation pipeline as `/db/query`. Failures are partial — successful queries still return results even if others fail. Batching is more efficient than sequential individual calls. 
     * Execute multiple SQL queries in batch
     */
    async dbBatchRaw(requestParameters: DbBatchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DbBatchResult>> {
        if (requestParameters.dbBatchRequest === null || requestParameters.dbBatchRequest === undefined) {
            throw new runtime.RequiredError('dbBatchRequest','Required parameter requestParameters.dbBatchRequest was null or undefined when calling dbBatch.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/db/batch`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DbBatchRequestToJSON(requestParameters.dbBatchRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DbBatchResultFromJSON(jsonValue));
    }

    /**
     * Run up to 25 SQL queries in a single request. Each query runs through the same sanitization and project-isolation pipeline as `/db/query`. Failures are partial — successful queries still return results even if others fail. Batching is more efficient than sequential individual calls. 
     * Execute multiple SQL queries in batch
     */
    async dbBatch(requestParameters: DbBatchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DbBatchResult> {
        const response = await this.dbBatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Run a SQL query against your project database
     * Execute SQL query
     */
    async dbQueryRaw(requestParameters: DbQueryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DbQueryResult>> {
        if (requestParameters.dbQueryRequest === null || requestParameters.dbQueryRequest === undefined) {
            throw new runtime.RequiredError('dbQueryRequest','Required parameter requestParameters.dbQueryRequest was null or undefined when calling dbQuery.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters.xRequestID !== undefined && requestParameters.xRequestID !== null) {
            headerParameters['X-Request-ID'] = String(requestParameters.xRequestID);
        }

        if (requestParameters.xSDKVersion !== undefined && requestParameters.xSDKVersion !== null) {
            headerParameters['X-SDK-Version'] = String(requestParameters.xSDKVersion);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/db/query`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DbQueryRequestToJSON(requestParameters.dbQueryRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DbQueryResultFromJSON(jsonValue));
    }

    /**
     * Run a SQL query against your project database
     * Execute SQL query
     */
    async dbQuery(requestParameters: DbQueryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DbQueryResult> {
        const response = await this.dbQueryRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
