/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  ChatCompletionRequest,
  ChatCompletionResponse,
  ErrorResponse,
  GatewayBillingLog200Response,
  GatewayBillingLogRequest,
  GatewayGetWallet200Response,
} from '../models/index.js';
import {
    ChatCompletionRequestFromJSON,
    ChatCompletionRequestToJSON,
    ChatCompletionResponseFromJSON,
    ChatCompletionResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    GatewayBillingLog200ResponseFromJSON,
    GatewayBillingLog200ResponseToJSON,
    GatewayBillingLogRequestFromJSON,
    GatewayBillingLogRequestToJSON,
    GatewayGetWallet200ResponseFromJSON,
    GatewayGetWallet200ResponseToJSON,
} from '../models/index.js';

export interface GatewayBillingLogOperationRequest {
    gatewayBillingLogRequest: GatewayBillingLogRequest;
}

export interface GatewayChatCompletionsRequest {
    apiSlug: string;
    chatCompletionRequest: ChatCompletionRequest;
}

export interface GatewayGetWalletRequest {
    apiSlug: string;
}

/**
 * 
 */
export class GatewayApi extends runtime.BaseAPI {

    /**
     * Manually log tokens or custom metric usage for a Gateway API
     * Log Gateway usage
     */
    async gatewayBillingLogRaw(requestParameters: GatewayBillingLogOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GatewayBillingLog200Response>> {
        if (requestParameters.gatewayBillingLogRequest === null || requestParameters.gatewayBillingLogRequest === undefined) {
            throw new runtime.RequiredError('gatewayBillingLogRequest','Required parameter requestParameters.gatewayBillingLogRequest was null or undefined when calling gatewayBillingLog.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/gateway/billing/log`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GatewayBillingLogRequestToJSON(requestParameters.gatewayBillingLogRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GatewayBillingLog200ResponseFromJSON(jsonValue));
    }

    /**
     * Manually log tokens or custom metric usage for a Gateway API
     * Log Gateway usage
     */
    async gatewayBillingLog(requestParameters: GatewayBillingLogOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GatewayBillingLog200Response> {
        const response = await this.gatewayBillingLogRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * OpenAI-compatible chat completions endpoint routed through a developer Gateway API. Supports streaming SSE, RAG pipeline, pre/post hooks, token metering, and consumer-key or JWT authentication.  The Gateway API slug identifies which developer-configured pipeline to use. Authenticate with a `consumerKey` (Bearer token) issued from the Gateway\'s consumer management, or with a user JWT from Aerostack Auth.  Streaming is supported — set `stream: true` to receive SSE token deltas. 
     * Gateway chat completions (OpenAI-compatible)
     */
    async gatewayChatCompletionsRaw(requestParameters: GatewayChatCompletionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChatCompletionResponse>> {
        if (requestParameters.apiSlug === null || requestParameters.apiSlug === undefined) {
            throw new runtime.RequiredError('apiSlug','Required parameter requestParameters.apiSlug was null or undefined when calling gatewayChatCompletions.');
        }

        if (requestParameters.chatCompletionRequest === null || requestParameters.chatCompletionRequest === undefined) {
            throw new runtime.RequiredError('chatCompletionRequest','Required parameter requestParameters.chatCompletionRequest was null or undefined when calling gatewayChatCompletions.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("GatewayConsumerKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/ai/gateway/{apiSlug}/chat/completions`.replace(`{${"apiSlug"}}`, encodeURIComponent(String(requestParameters.apiSlug))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChatCompletionRequestToJSON(requestParameters.chatCompletionRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChatCompletionResponseFromJSON(jsonValue));
    }

    /**
     * OpenAI-compatible chat completions endpoint routed through a developer Gateway API. Supports streaming SSE, RAG pipeline, pre/post hooks, token metering, and consumer-key or JWT authentication.  The Gateway API slug identifies which developer-configured pipeline to use. Authenticate with a `consumerKey` (Bearer token) issued from the Gateway\'s consumer management, or with a user JWT from Aerostack Auth.  Streaming is supported — set `stream: true` to receive SSE token deltas. 
     * Gateway chat completions (OpenAI-compatible)
     */
    async gatewayChatCompletions(requestParameters: GatewayChatCompletionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChatCompletionResponse> {
        const response = await this.gatewayChatCompletionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the remaining token balance and total consumed for the authenticated consumer (identified by Bearer token or consumer key). 
     * Get consumer token wallet balance
     */
    async gatewayGetWalletRaw(requestParameters: GatewayGetWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GatewayGetWallet200Response>> {
        if (requestParameters.apiSlug === null || requestParameters.apiSlug === undefined) {
            throw new runtime.RequiredError('apiSlug','Required parameter requestParameters.apiSlug was null or undefined when calling gatewayGetWallet.');
        }

        const queryParameters: any = {};

        if (requestParameters.apiSlug !== undefined) {
            queryParameters['api_slug'] = requestParameters.apiSlug;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("GatewayConsumerKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/ai/gateway/me/wallet`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GatewayGetWallet200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns the remaining token balance and total consumed for the authenticated consumer (identified by Bearer token or consumer key). 
     * Get consumer token wallet balance
     */
    async gatewayGetWallet(requestParameters: GatewayGetWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GatewayGetWallet200Response> {
        const response = await this.gatewayGetWalletRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
