/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  ErrorResponse,
  GatewayBillingLog200Response,
  GatewayBillingLogRequest,
} from '../models/index.js';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    GatewayBillingLog200ResponseFromJSON,
    GatewayBillingLog200ResponseToJSON,
    GatewayBillingLogRequestFromJSON,
    GatewayBillingLogRequestToJSON,
} from '../models/index.js';

export interface GatewayBillingLogOperationRequest {
    gatewayBillingLogRequest: GatewayBillingLogRequest;
}

/**
 * 
 */
export class GatewayApi extends runtime.BaseAPI {

    /**
     * Manually log tokens or custom metric usage for a Gateway API
     * Log Gateway usage
     */
    async gatewayBillingLogRaw(requestParameters: GatewayBillingLogOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GatewayBillingLog200Response>> {
        if (requestParameters.gatewayBillingLogRequest === null || requestParameters.gatewayBillingLogRequest === undefined) {
            throw new runtime.RequiredError('gatewayBillingLogRequest','Required parameter requestParameters.gatewayBillingLogRequest was null or undefined when calling gatewayBillingLog.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/gateway/billing/log`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GatewayBillingLogRequestToJSON(requestParameters.gatewayBillingLogRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GatewayBillingLog200ResponseFromJSON(jsonValue));
    }

    /**
     * Manually log tokens or custom metric usage for a Gateway API
     * Log Gateway usage
     */
    async gatewayBillingLog(requestParameters: GatewayBillingLogOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GatewayBillingLog200Response> {
        const response = await this.gatewayBillingLogRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
