/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  QueueEnqueue201Response,
  QueueEnqueueRequest,
} from '../models/index.js';
import {
    QueueEnqueue201ResponseFromJSON,
    QueueEnqueue201ResponseToJSON,
    QueueEnqueueRequestFromJSON,
    QueueEnqueueRequestToJSON,
} from '../models/index.js';

export interface QueueEnqueueOperationRequest {
    queueEnqueueRequest: QueueEnqueueRequest;
}

/**
 * 
 */
export class QueueApi extends runtime.BaseAPI {

    /**
     * Add job to queue
     */
    async queueEnqueueRaw(requestParameters: QueueEnqueueOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueueEnqueue201Response>> {
        if (requestParameters.queueEnqueueRequest === null || requestParameters.queueEnqueueRequest === undefined) {
            throw new runtime.RequiredError('queueEnqueueRequest','Required parameter requestParameters.queueEnqueueRequest was null or undefined when calling queueEnqueue.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/queue/enqueue`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: QueueEnqueueRequestToJSON(requestParameters.queueEnqueueRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QueueEnqueue201ResponseFromJSON(jsonValue));
    }

    /**
     * Add job to queue
     */
    async queueEnqueue(requestParameters: QueueEnqueueOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueueEnqueue201Response> {
        const response = await this.queueEnqueueRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
