/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  QueueCancelJob200Response,
  QueueEnqueue201Response,
  QueueEnqueueRequest,
  QueueGetJob200Response,
  QueueGetJobRequest,
  QueueListJobs200Response,
  QueueListJobsRequest,
} from '../models/index.js';
import {
    QueueCancelJob200ResponseFromJSON,
    QueueCancelJob200ResponseToJSON,
    QueueEnqueue201ResponseFromJSON,
    QueueEnqueue201ResponseToJSON,
    QueueEnqueueRequestFromJSON,
    QueueEnqueueRequestToJSON,
    QueueGetJob200ResponseFromJSON,
    QueueGetJob200ResponseToJSON,
    QueueGetJobRequestFromJSON,
    QueueGetJobRequestToJSON,
    QueueListJobs200ResponseFromJSON,
    QueueListJobs200ResponseToJSON,
    QueueListJobsRequestFromJSON,
    QueueListJobsRequestToJSON,
} from '../models/index.js';

export interface QueueCancelJobRequest {
    queueGetJobRequest: QueueGetJobRequest;
}

export interface QueueEnqueueOperationRequest {
    queueEnqueueRequest: QueueEnqueueRequest;
}

export interface QueueGetJobOperationRequest {
    queueGetJobRequest: QueueGetJobRequest;
}

export interface QueueListJobsOperationRequest {
    queueListJobsRequest: QueueListJobsRequest;
}

/**
 * 
 */
export class QueueApi extends runtime.BaseAPI {

    /**
     * Marks a job as `cancelled` in the job store. This is advisory only — if a consumer Worker has already picked up the job, it will still execute unless the consumer explicitly checks job status before processing. Cannot cancel jobs already in `completed` or `failed` state. 
     * Cancel a queued job
     */
    async queueCancelJobRaw(requestParameters: QueueCancelJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueueCancelJob200Response>> {
        if (requestParameters.queueGetJobRequest === null || requestParameters.queueGetJobRequest === undefined) {
            throw new runtime.RequiredError('queueGetJobRequest','Required parameter requestParameters.queueGetJobRequest was null or undefined when calling queueCancelJob.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/queue/cancel`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: QueueGetJobRequestToJSON(requestParameters.queueGetJobRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QueueCancelJob200ResponseFromJSON(jsonValue));
    }

    /**
     * Marks a job as `cancelled` in the job store. This is advisory only — if a consumer Worker has already picked up the job, it will still execute unless the consumer explicitly checks job status before processing. Cannot cancel jobs already in `completed` or `failed` state. 
     * Cancel a queued job
     */
    async queueCancelJob(requestParameters: QueueCancelJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueueCancelJob200Response> {
        const response = await this.queueCancelJobRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Enqueues a job for background processing. Returns a `jobId` that can be used with `/queue/job` to track status. Job metadata is persisted for 7 days. 
     * Add job to queue
     */
    async queueEnqueueRaw(requestParameters: QueueEnqueueOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueueEnqueue201Response>> {
        if (requestParameters.queueEnqueueRequest === null || requestParameters.queueEnqueueRequest === undefined) {
            throw new runtime.RequiredError('queueEnqueueRequest','Required parameter requestParameters.queueEnqueueRequest was null or undefined when calling queueEnqueue.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/queue/enqueue`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: QueueEnqueueRequestToJSON(requestParameters.queueEnqueueRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QueueEnqueue201ResponseFromJSON(jsonValue));
    }

    /**
     * Enqueues a job for background processing. Returns a `jobId` that can be used with `/queue/job` to track status. Job metadata is persisted for 7 days. 
     * Add job to queue
     */
    async queueEnqueue(requestParameters: QueueEnqueueOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueueEnqueue201Response> {
        const response = await this.queueEnqueueRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get job status by ID
     */
    async queueGetJobRaw(requestParameters: QueueGetJobOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueueGetJob200Response>> {
        if (requestParameters.queueGetJobRequest === null || requestParameters.queueGetJobRequest === undefined) {
            throw new runtime.RequiredError('queueGetJobRequest','Required parameter requestParameters.queueGetJobRequest was null or undefined when calling queueGetJob.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/queue/job`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: QueueGetJobRequestToJSON(requestParameters.queueGetJobRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QueueGetJob200ResponseFromJSON(jsonValue));
    }

    /**
     * Get job status by ID
     */
    async queueGetJob(requestParameters: QueueGetJobOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueueGetJob200Response> {
        const response = await this.queueGetJobRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns paginated job records. Filter by `status` (queued, processing, completed, failed, cancelled) or `type`. Uses cursor-based pagination. Job metadata is retained for 7 days. 
     * List jobs with optional filters
     */
    async queueListJobsRaw(requestParameters: QueueListJobsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueueListJobs200Response>> {
        if (requestParameters.queueListJobsRequest === null || requestParameters.queueListJobsRequest === undefined) {
            throw new runtime.RequiredError('queueListJobsRequest','Required parameter requestParameters.queueListJobsRequest was null or undefined when calling queueListJobs.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/queue/jobs`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: QueueListJobsRequestToJSON(requestParameters.queueListJobsRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QueueListJobs200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns paginated job records. Filter by `status` (queued, processing, completed, failed, cancelled) or `type`. Uses cursor-based pagination. Job metadata is retained for 7 days. 
     * List jobs with optional filters
     */
    async queueListJobs(requestParameters: QueueListJobsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueueListJobs200Response> {
        const response = await this.queueListJobsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
