/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  ServicesInvoke200Response,
  ServicesInvokeRequest,
} from '../models/index.js';
import {
    ServicesInvoke200ResponseFromJSON,
    ServicesInvoke200ResponseToJSON,
    ServicesInvokeRequestFromJSON,
    ServicesInvokeRequestToJSON,
} from '../models/index.js';

export interface ServicesInvokeOperationRequest {
    servicesInvokeRequest: ServicesInvokeRequest;
}

/**
 * 
 */
export class ServicesApi extends runtime.BaseAPI {

    /**
     * Invoke another service
     */
    async servicesInvokeRaw(requestParameters: ServicesInvokeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServicesInvoke200Response>> {
        if (requestParameters.servicesInvokeRequest === null || requestParameters.servicesInvokeRequest === undefined) {
            throw new runtime.RequiredError('servicesInvokeRequest','Required parameter requestParameters.servicesInvokeRequest was null or undefined when calling servicesInvoke.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/services/invoke`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ServicesInvokeRequestToJSON(requestParameters.servicesInvokeRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServicesInvoke200ResponseFromJSON(jsonValue));
    }

    /**
     * Invoke another service
     */
    async servicesInvoke(requestParameters: ServicesInvokeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServicesInvoke200Response> {
        const response = await this.servicesInvokeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
