/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  CacheSet200Response,
  ErrorResponse,
  StorageCopy200Response,
  StorageCopyRequest,
  StorageExists200Response,
  StorageGetRequest,
  StorageListRequest,
  StorageListResult,
  StorageMetadata,
  StorageMove200Response,
  StorageMoveRequest,
  StorageUpload200Response,
} from '../models/index.js';
import {
    CacheSet200ResponseFromJSON,
    CacheSet200ResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    StorageCopy200ResponseFromJSON,
    StorageCopy200ResponseToJSON,
    StorageCopyRequestFromJSON,
    StorageCopyRequestToJSON,
    StorageExists200ResponseFromJSON,
    StorageExists200ResponseToJSON,
    StorageGetRequestFromJSON,
    StorageGetRequestToJSON,
    StorageListRequestFromJSON,
    StorageListRequestToJSON,
    StorageListResultFromJSON,
    StorageListResultToJSON,
    StorageMetadataFromJSON,
    StorageMetadataToJSON,
    StorageMove200ResponseFromJSON,
    StorageMove200ResponseToJSON,
    StorageMoveRequestFromJSON,
    StorageMoveRequestToJSON,
    StorageUpload200ResponseFromJSON,
    StorageUpload200ResponseToJSON,
} from '../models/index.js';

export interface StorageCopyOperationRequest {
    storageCopyRequest: StorageCopyRequest;
}

export interface StorageDeleteRequest {
    storageGetRequest: StorageGetRequest;
}

export interface StorageExistsRequest {
    storageGetRequest: StorageGetRequest;
}

export interface StorageGetOperationRequest {
    storageGetRequest: StorageGetRequest;
}

export interface StorageGetMetadataRequest {
    storageGetRequest: StorageGetRequest;
}

export interface StorageGetUrlRequest {
    storageGetRequest: StorageGetRequest;
}

export interface StorageListOperationRequest {
    storageListRequest: StorageListRequest;
}

export interface StorageMoveOperationRequest {
    storageMoveRequest: StorageMoveRequest;
}

export interface StorageUploadRequest {
    file: Blob;
    key: string;
    contentType?: string;
}

/**
 * 
 */
export class StorageApi extends runtime.BaseAPI {

    /**
     * Streams the source file directly to the destination without buffering in memory. Both source and destination must be within your project\'s storage namespace. 
     * Copy a file to a new key
     */
    async storageCopyRaw(requestParameters: StorageCopyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StorageCopy200Response>> {
        if (requestParameters.storageCopyRequest === null || requestParameters.storageCopyRequest === undefined) {
            throw new runtime.RequiredError('storageCopyRequest','Required parameter requestParameters.storageCopyRequest was null or undefined when calling storageCopy.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/storage/copy`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StorageCopyRequestToJSON(requestParameters.storageCopyRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StorageCopy200ResponseFromJSON(jsonValue));
    }

    /**
     * Streams the source file directly to the destination without buffering in memory. Both source and destination must be within your project\'s storage namespace. 
     * Copy a file to a new key
     */
    async storageCopy(requestParameters: StorageCopyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StorageCopy200Response> {
        const response = await this.storageCopyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a file from storage
     */
    async storageDeleteRaw(requestParameters: StorageDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CacheSet200Response>> {
        if (requestParameters.storageGetRequest === null || requestParameters.storageGetRequest === undefined) {
            throw new runtime.RequiredError('storageGetRequest','Required parameter requestParameters.storageGetRequest was null or undefined when calling storageDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/storage/delete`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StorageGetRequestToJSON(requestParameters.storageGetRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CacheSet200ResponseFromJSON(jsonValue));
    }

    /**
     * Delete a file from storage
     */
    async storageDelete(requestParameters: StorageDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CacheSet200Response> {
        const response = await this.storageDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Uses a lightweight HEAD request — more efficient than `get` for existence checks.
     * Check if a file exists
     */
    async storageExistsRaw(requestParameters: StorageExistsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StorageExists200Response>> {
        if (requestParameters.storageGetRequest === null || requestParameters.storageGetRequest === undefined) {
            throw new runtime.RequiredError('storageGetRequest','Required parameter requestParameters.storageGetRequest was null or undefined when calling storageExists.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/storage/exists`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StorageGetRequestToJSON(requestParameters.storageGetRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StorageExists200ResponseFromJSON(jsonValue));
    }

    /**
     * Uses a lightweight HEAD request — more efficient than `get` for existence checks.
     * Check if a file exists
     */
    async storageExists(requestParameters: StorageExistsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StorageExists200Response> {
        const response = await this.storageExistsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the raw binary content of the file. The response body is the file data with the appropriate `Content-Type` header set. Returns 404 if the key does not exist.  **Note for SDK users**: `storage.get()` returns the raw `Response` object — use `.arrayBuffer()`, `.blob()`, or `.text()` to read the content. 
     * Download file from storage
     */
    async storageGetRaw(requestParameters: StorageGetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters.storageGetRequest === null || requestParameters.storageGetRequest === undefined) {
            throw new runtime.RequiredError('storageGetRequest','Required parameter requestParameters.storageGetRequest was null or undefined when calling storageGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/storage/get`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StorageGetRequestToJSON(requestParameters.storageGetRequest),
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Returns the raw binary content of the file. The response body is the file data with the appropriate `Content-Type` header set. Returns 404 if the key does not exist.  **Note for SDK users**: `storage.get()` returns the raw `Response` object — use `.arrayBuffer()`, `.blob()`, or `.text()` to read the content. 
     * Download file from storage
     */
    async storageGet(requestParameters: StorageGetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.storageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get file metadata without downloading content
     */
    async storageGetMetadataRaw(requestParameters: StorageGetMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StorageMetadata>> {
        if (requestParameters.storageGetRequest === null || requestParameters.storageGetRequest === undefined) {
            throw new runtime.RequiredError('storageGetRequest','Required parameter requestParameters.storageGetRequest was null or undefined when calling storageGetMetadata.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/storage/getMetadata`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StorageGetRequestToJSON(requestParameters.storageGetRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StorageMetadataFromJSON(jsonValue));
    }

    /**
     * Get file metadata without downloading content
     */
    async storageGetMetadata(requestParameters: StorageGetMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StorageMetadata> {
        const response = await this.storageGetMetadataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the public CDN URL for the given storage key without downloading the file content.
     * Get public CDN URL for a stored file
     */
    async storageGetUrlRaw(requestParameters: StorageGetUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StorageUpload200Response>> {
        if (requestParameters.storageGetRequest === null || requestParameters.storageGetRequest === undefined) {
            throw new runtime.RequiredError('storageGetRequest','Required parameter requestParameters.storageGetRequest was null or undefined when calling storageGetUrl.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/storage/getUrl`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StorageGetRequestToJSON(requestParameters.storageGetRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StorageUpload200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns the public CDN URL for the given storage key without downloading the file content.
     * Get public CDN URL for a stored file
     */
    async storageGetUrl(requestParameters: StorageGetUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StorageUpload200Response> {
        const response = await this.storageGetUrlRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns paginated list of files matching an optional prefix. Uses cursor-based pagination.
     * List stored files with prefix
     */
    async storageListRaw(requestParameters: StorageListOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StorageListResult>> {
        if (requestParameters.storageListRequest === null || requestParameters.storageListRequest === undefined) {
            throw new runtime.RequiredError('storageListRequest','Required parameter requestParameters.storageListRequest was null or undefined when calling storageList.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/storage/list`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StorageListRequestToJSON(requestParameters.storageListRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StorageListResultFromJSON(jsonValue));
    }

    /**
     * Returns paginated list of files matching an optional prefix. Uses cursor-based pagination.
     * List stored files with prefix
     */
    async storageList(requestParameters: StorageListOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StorageListResult> {
        const response = await this.storageListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Copies the source file to the destination then deletes the source. Not atomic — if the delete fails after a successful copy, both keys will exist. 
     * Move a file to a new key
     */
    async storageMoveRaw(requestParameters: StorageMoveOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StorageMove200Response>> {
        if (requestParameters.storageMoveRequest === null || requestParameters.storageMoveRequest === undefined) {
            throw new runtime.RequiredError('storageMoveRequest','Required parameter requestParameters.storageMoveRequest was null or undefined when calling storageMove.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/storage/move`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StorageMoveRequestToJSON(requestParameters.storageMoveRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StorageMove200ResponseFromJSON(jsonValue));
    }

    /**
     * Copies the source file to the destination then deletes the source. Not atomic — if the delete fails after a successful copy, both keys will exist. 
     * Move a file to a new key
     */
    async storageMove(requestParameters: StorageMoveOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StorageMove200Response> {
        const response = await this.storageMoveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload file to storage
     */
    async storageUploadRaw(requestParameters: StorageUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StorageUpload200Response>> {
        if (requestParameters.file === null || requestParameters.file === undefined) {
            throw new runtime.RequiredError('file','Required parameter requestParameters.file was null or undefined when calling storageUpload.');
        }

        if (requestParameters.key === null || requestParameters.key === undefined) {
            throw new runtime.RequiredError('key','Required parameter requestParameters.key was null or undefined when calling storageUpload.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Aerostack-Key"] = this.configuration.apiKey("X-Aerostack-Key"); // ApiKeyAuth authentication
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters.file !== undefined) {
            formParams.append('file', requestParameters.file as any);
        }

        if (requestParameters.key !== undefined) {
            formParams.append('key', requestParameters.key as any);
        }

        if (requestParameters.contentType !== undefined) {
            formParams.append('contentType', requestParameters.contentType as any);
        }

        const response = await this.request({
            path: `/storage/upload`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StorageUpload200ResponseFromJSON(jsonValue));
    }

    /**
     * Upload file to storage
     */
    async storageUpload(requestParameters: StorageUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StorageUpload200Response> {
        const response = await this.storageUploadRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
