/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface AiChatRequestMessagesInner
 */
export interface AiChatRequestMessagesInner {
    /**
     * 
     * @type {string}
     * @memberof AiChatRequestMessagesInner
     */
    role?: AiChatRequestMessagesInnerRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof AiChatRequestMessagesInner
     */
    content?: string;
}


/**
 * @export
 */
export const AiChatRequestMessagesInnerRoleEnum = {
    System: 'system',
    User: 'user',
    Assistant: 'assistant'
} as const;
export type AiChatRequestMessagesInnerRoleEnum = typeof AiChatRequestMessagesInnerRoleEnum[keyof typeof AiChatRequestMessagesInnerRoleEnum];


/**
 * Check if a given object implements the AiChatRequestMessagesInner interface.
 */
export function instanceOfAiChatRequestMessagesInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AiChatRequestMessagesInnerFromJSON(json: any): AiChatRequestMessagesInner {
    return AiChatRequestMessagesInnerFromJSONTyped(json, false);
}

export function AiChatRequestMessagesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiChatRequestMessagesInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'role': !exists(json, 'role') ? undefined : json['role'],
        'content': !exists(json, 'content') ? undefined : json['content'],
    };
}

export function AiChatRequestMessagesInnerToJSON(value?: AiChatRequestMessagesInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'role': value.role,
        'content': value.content,
    };
}

