/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
import type { AiChatRequestMessagesInner } from './AiChatRequestMessagesInner.js';
import {
    AiChatRequestMessagesInnerFromJSON,
    AiChatRequestMessagesInnerFromJSONTyped,
    AiChatRequestMessagesInnerToJSON,
} from './AiChatRequestMessagesInner.js';

/**
 * 
 * @export
 * @interface AiChatRequest
 */
export interface AiChatRequest {
    /**
     * 
     * @type {string}
     * @memberof AiChatRequest
     */
    model?: string;
    /**
     * 
     * @type {Array<AiChatRequestMessagesInner>}
     * @memberof AiChatRequest
     */
    messages: Array<AiChatRequestMessagesInner>;
}

/**
 * Check if a given object implements the AiChatRequest interface.
 */
export function instanceOfAiChatRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "messages" in value;

    return isInstance;
}

export function AiChatRequestFromJSON(json: any): AiChatRequest {
    return AiChatRequestFromJSONTyped(json, false);
}

export function AiChatRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiChatRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'model': !exists(json, 'model') ? undefined : json['model'],
        'messages': ((json['messages'] as Array<any>).map(AiChatRequestMessagesInnerFromJSON)),
    };
}

export function AiChatRequestToJSON(value?: AiChatRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'model': value.model,
        'messages': ((value.messages as Array<any>).map(AiChatRequestMessagesInnerToJSON)),
    };
}

