/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface AiChat200Response
 */
export interface AiChat200Response {
    /**
     * 
     * @type {string}
     * @memberof AiChat200Response
     */
    response?: string;
}

/**
 * Check if a given object implements the AiChat200Response interface.
 */
export function instanceOfAiChat200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AiChat200ResponseFromJSON(json: any): AiChat200Response {
    return AiChat200ResponseFromJSONTyped(json, false);
}

export function AiChat200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiChat200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : json['response'],
    };
}

export function AiChat200ResponseToJSON(value?: AiChat200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': value.response,
    };
}

