/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface AuthSignupRequest
 */
export interface AuthSignupRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthSignupRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AuthSignupRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof AuthSignupRequest
     */
    name?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof AuthSignupRequest
     */
    metadata?: { [key: string]: any; } | null;
}

/**
 * Check if a given object implements the AuthSignupRequest interface.
 */
export function instanceOfAuthSignupRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function AuthSignupRequestFromJSON(json: any): AuthSignupRequest {
    return AuthSignupRequestFromJSONTyped(json, false);
}

export function AuthSignupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthSignupRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
    };
}

export function AuthSignupRequestToJSON(value?: AuthSignupRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
        'name': value.name,
        'metadata': value.metadata,
    };
}

