/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface AuthSigninRequest
 */
export interface AuthSigninRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthSigninRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AuthSigninRequest
     */
    password: string;
}

/**
 * Check if a given object implements the AuthSigninRequest interface.
 */
export function instanceOfAuthSigninRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function AuthSigninRequestFromJSON(json: any): AuthSigninRequest {
    return AuthSigninRequestFromJSONTyped(json, false);
}

export function AuthSigninRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthSigninRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function AuthSigninRequestToJSON(value?: AuthSigninRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
    };
}

