/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CacheGetManyRequest
 */
export interface CacheGetManyRequest {
    /**
     * Keys to fetch (max 100)
     * @type {Array<string>}
     * @memberof CacheGetManyRequest
     */
    keys: Array<string>;
}

/**
 * Check if a given object implements the CacheGetManyRequest interface.
 */
export function instanceOfCacheGetManyRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "keys" in value;

    return isInstance;
}

export function CacheGetManyRequestFromJSON(json: any): CacheGetManyRequest {
    return CacheGetManyRequestFromJSONTyped(json, false);
}

export function CacheGetManyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CacheGetManyRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'keys': json['keys'],
    };
}

export function CacheGetManyRequestToJSON(value?: CacheGetManyRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'keys': value.keys,
    };
}

