/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CacheGetManyEntry
 */
export interface CacheGetManyEntry {
    /**
     * 
     * @type {string}
     * @memberof CacheGetManyEntry
     */
    key?: string;
    /**
     * 
     * @type {any}
     * @memberof CacheGetManyEntry
     */
    value?: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof CacheGetManyEntry
     */
    _exists?: boolean;
}

/**
 * Check if a given object implements the CacheGetManyEntry interface.
 */
export function instanceOfCacheGetManyEntry(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CacheGetManyEntryFromJSON(json: any): CacheGetManyEntry {
    return CacheGetManyEntryFromJSONTyped(json, false);
}

export function CacheGetManyEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CacheGetManyEntry {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': !exists(json, 'key') ? undefined : json['key'],
        'value': !exists(json, 'value') ? undefined : json['value'],
        '_exists': !exists(json, 'exists') ? undefined : json['exists'],
    };
}

export function CacheGetManyEntryToJSON(value?: CacheGetManyEntry | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'value': value.value,
        'exists': value._exists,
    };
}

