/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
import type { CacheGetManyEntry } from './CacheGetManyEntry.js';
import {
    CacheGetManyEntryFromJSON,
    CacheGetManyEntryFromJSONTyped,
    CacheGetManyEntryToJSON,
} from './CacheGetManyEntry.js';

/**
 * 
 * @export
 * @interface CacheGetMany200Response
 */
export interface CacheGetMany200Response {
    /**
     * 
     * @type {Array<CacheGetManyEntry>}
     * @memberof CacheGetMany200Response
     */
    results?: Array<CacheGetManyEntry>;
}

/**
 * Check if a given object implements the CacheGetMany200Response interface.
 */
export function instanceOfCacheGetMany200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CacheGetMany200ResponseFromJSON(json: any): CacheGetMany200Response {
    return CacheGetMany200ResponseFromJSONTyped(json, false);
}

export function CacheGetMany200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CacheGetMany200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(CacheGetManyEntryFromJSON)),
    };
}

export function CacheGetMany200ResponseToJSON(value?: CacheGetMany200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(CacheGetManyEntryToJSON)),
    };
}

