/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
import type { CacheKeyEntry } from './CacheKeyEntry.js';
import {
    CacheKeyEntryFromJSON,
    CacheKeyEntryFromJSONTyped,
    CacheKeyEntryToJSON,
} from './CacheKeyEntry.js';

/**
 * 
 * @export
 * @interface CacheListResult
 */
export interface CacheListResult {
    /**
     * 
     * @type {Array<CacheKeyEntry>}
     * @memberof CacheListResult
     */
    keys?: Array<CacheKeyEntry>;
    /**
     * True if all keys were returned; false if more pages exist
     * @type {boolean}
     * @memberof CacheListResult
     */
    listComplete?: boolean;
    /**
     * Use this cursor to fetch the next page
     * @type {string}
     * @memberof CacheListResult
     */
    cursor?: string;
}

/**
 * Check if a given object implements the CacheListResult interface.
 */
export function instanceOfCacheListResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CacheListResultFromJSON(json: any): CacheListResult {
    return CacheListResultFromJSONTyped(json, false);
}

export function CacheListResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CacheListResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'keys': !exists(json, 'keys') ? undefined : ((json['keys'] as Array<any>).map(CacheKeyEntryFromJSON)),
        'listComplete': !exists(json, 'list_complete') ? undefined : json['list_complete'],
        'cursor': !exists(json, 'cursor') ? undefined : json['cursor'],
    };
}

export function CacheListResultToJSON(value?: CacheListResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'keys': value.keys === undefined ? undefined : ((value.keys as Array<any>).map(CacheKeyEntryToJSON)),
        'list_complete': value.listComplete,
        'cursor': value.cursor,
    };
}

