/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CacheFlushRequest
 */
export interface CacheFlushRequest {
    /**
     * Key prefix to flush. Omit to flush all project keys.
     * @type {string}
     * @memberof CacheFlushRequest
     */
    prefix?: string;
}

/**
 * Check if a given object implements the CacheFlushRequest interface.
 */
export function instanceOfCacheFlushRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CacheFlushRequestFromJSON(json: any): CacheFlushRequest {
    return CacheFlushRequestFromJSONTyped(json, false);
}

export function CacheFlushRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CacheFlushRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'prefix': !exists(json, 'prefix') ? undefined : json['prefix'],
    };
}

export function CacheFlushRequestToJSON(value?: CacheFlushRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'prefix': value.prefix,
    };
}

