/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CacheKeysRequest
 */
export interface CacheKeysRequest {
    /**
     * Key prefix to filter by
     * @type {string}
     * @memberof CacheKeysRequest
     */
    prefix?: string;
}

/**
 * Check if a given object implements the CacheKeysRequest interface.
 */
export function instanceOfCacheKeysRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CacheKeysRequestFromJSON(json: any): CacheKeysRequest {
    return CacheKeysRequestFromJSONTyped(json, false);
}

export function CacheKeysRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CacheKeysRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'prefix': !exists(json, 'prefix') ? undefined : json['prefix'],
    };
}

export function CacheKeysRequestToJSON(value?: CacheKeysRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'prefix': value.prefix,
    };
}

