/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CacheDeleteManyRequest
 */
export interface CacheDeleteManyRequest {
    /**
     * Keys to delete (max 500)
     * @type {Array<string>}
     * @memberof CacheDeleteManyRequest
     */
    keys: Array<string>;
}

/**
 * Check if a given object implements the CacheDeleteManyRequest interface.
 */
export function instanceOfCacheDeleteManyRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "keys" in value;

    return isInstance;
}

export function CacheDeleteManyRequestFromJSON(json: any): CacheDeleteManyRequest {
    return CacheDeleteManyRequestFromJSONTyped(json, false);
}

export function CacheDeleteManyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CacheDeleteManyRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'keys': json['keys'],
    };
}

export function CacheDeleteManyRequestToJSON(value?: CacheDeleteManyRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'keys': value.keys,
    };
}

