/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
import type { CacheSetEntry } from './CacheSetEntry.js';
import {
    CacheSetEntryFromJSON,
    CacheSetEntryFromJSONTyped,
    CacheSetEntryToJSON,
} from './CacheSetEntry.js';

/**
 * 
 * @export
 * @interface CacheSetManyRequest
 */
export interface CacheSetManyRequest {
    /**
     * Entries to cache (max 100)
     * @type {Array<CacheSetEntry>}
     * @memberof CacheSetManyRequest
     */
    entries: Array<CacheSetEntry>;
}

/**
 * Check if a given object implements the CacheSetManyRequest interface.
 */
export function instanceOfCacheSetManyRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "entries" in value;

    return isInstance;
}

export function CacheSetManyRequestFromJSON(json: any): CacheSetManyRequest {
    return CacheSetManyRequestFromJSONTyped(json, false);
}

export function CacheSetManyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CacheSetManyRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'entries': ((json['entries'] as Array<any>).map(CacheSetEntryFromJSON)),
    };
}

export function CacheSetManyRequestToJSON(value?: CacheSetManyRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'entries': ((value.entries as Array<any>).map(CacheSetEntryToJSON)),
    };
}

