/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CacheSetEntry
 */
export interface CacheSetEntry {
    /**
     * 
     * @type {string}
     * @memberof CacheSetEntry
     */
    key: string;
    /**
     * 
     * @type {any}
     * @memberof CacheSetEntry
     */
    value: any | null;
    /**
     * Time to live in seconds
     * @type {number}
     * @memberof CacheSetEntry
     */
    ttl?: number;
}

/**
 * Check if a given object implements the CacheSetEntry interface.
 */
export function instanceOfCacheSetEntry(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function CacheSetEntryFromJSON(json: any): CacheSetEntry {
    return CacheSetEntryFromJSONTyped(json, false);
}

export function CacheSetEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CacheSetEntry {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
        'value': json['value'],
        'ttl': !exists(json, 'ttl') ? undefined : json['ttl'],
    };
}

export function CacheSetEntryToJSON(value?: CacheSetEntry | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'value': value.value,
        'ttl': value.ttl,
    };
}

