/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CacheListRequest
 */
export interface CacheListRequest {
    /**
     * Key prefix to filter by (e.g. "users:")
     * @type {string}
     * @memberof CacheListRequest
     */
    prefix?: string;
    /**
     * Max keys to return per page (default 100, max 1000)
     * @type {number}
     * @memberof CacheListRequest
     */
    limit?: number;
    /**
     * Pagination cursor from previous response
     * @type {string}
     * @memberof CacheListRequest
     */
    cursor?: string;
}

/**
 * Check if a given object implements the CacheListRequest interface.
 */
export function instanceOfCacheListRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CacheListRequestFromJSON(json: any): CacheListRequest {
    return CacheListRequestFromJSONTyped(json, false);
}

export function CacheListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CacheListRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'prefix': !exists(json, 'prefix') ? undefined : json['prefix'],
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'cursor': !exists(json, 'cursor') ? undefined : json['cursor'],
    };
}

export function CacheListRequestToJSON(value?: CacheListRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'prefix': value.prefix,
        'limit': value.limit,
        'cursor': value.cursor,
    };
}

