/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CacheIncrement200Response
 */
export interface CacheIncrement200Response {
    /**
     * New value after increment
     * @type {number}
     * @memberof CacheIncrement200Response
     */
    value?: number;
}

/**
 * Check if a given object implements the CacheIncrement200Response interface.
 */
export function instanceOfCacheIncrement200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CacheIncrement200ResponseFromJSON(json: any): CacheIncrement200Response {
    return CacheIncrement200ResponseFromJSONTyped(json, false);
}

export function CacheIncrement200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CacheIncrement200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function CacheIncrement200ResponseToJSON(value?: CacheIncrement200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
    };
}

