/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CacheKeyEntry
 */
export interface CacheKeyEntry {
    /**
     * Cache key (project prefix stripped)
     * @type {string}
     * @memberof CacheKeyEntry
     */
    key?: string;
    /**
     * Unix timestamp when this key expires (null if no TTL)
     * @type {number}
     * @memberof CacheKeyEntry
     */
    expiration?: number;
}

/**
 * Check if a given object implements the CacheKeyEntry interface.
 */
export function instanceOfCacheKeyEntry(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CacheKeyEntryFromJSON(json: any): CacheKeyEntry {
    return CacheKeyEntryFromJSONTyped(json, false);
}

export function CacheKeyEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CacheKeyEntry {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': !exists(json, 'key') ? undefined : json['key'],
        'expiration': !exists(json, 'expiration') ? undefined : json['expiration'],
    };
}

export function CacheKeyEntryToJSON(value?: CacheKeyEntry | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'expiration': value.expiration,
    };
}

