/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CacheDeleteMany200Response
 */
export interface CacheDeleteMany200Response {
    /**
     * 
     * @type {boolean}
     * @memberof CacheDeleteMany200Response
     */
    success?: boolean;
    /**
     * Number of keys requested for deletion
     * @type {number}
     * @memberof CacheDeleteMany200Response
     */
    count?: number;
    /**
     * Number of keys actually deleted
     * @type {number}
     * @memberof CacheDeleteMany200Response
     */
    deleted?: number;
}

/**
 * Check if a given object implements the CacheDeleteMany200Response interface.
 */
export function instanceOfCacheDeleteMany200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CacheDeleteMany200ResponseFromJSON(json: any): CacheDeleteMany200Response {
    return CacheDeleteMany200ResponseFromJSONTyped(json, false);
}

export function CacheDeleteMany200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CacheDeleteMany200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'count': !exists(json, 'count') ? undefined : json['count'],
        'deleted': !exists(json, 'deleted') ? undefined : json['deleted'],
    };
}

export function CacheDeleteMany200ResponseToJSON(value?: CacheDeleteMany200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'count': value.count,
        'deleted': value.deleted,
    };
}

