/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CacheFlush200Response
 */
export interface CacheFlush200Response {
    /**
     * 
     * @type {boolean}
     * @memberof CacheFlush200Response
     */
    success?: boolean;
    /**
     * Number of keys deleted
     * @type {number}
     * @memberof CacheFlush200Response
     */
    deleted?: number;
}

/**
 * Check if a given object implements the CacheFlush200Response interface.
 */
export function instanceOfCacheFlush200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CacheFlush200ResponseFromJSON(json: any): CacheFlush200Response {
    return CacheFlush200ResponseFromJSONTyped(json, false);
}

export function CacheFlush200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CacheFlush200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'deleted': !exists(json, 'deleted') ? undefined : json['deleted'],
    };
}

export function CacheFlush200ResponseToJSON(value?: CacheFlush200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'deleted': value.deleted,
    };
}

