/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CacheKeys200Response
 */
export interface CacheKeys200Response {
    /**
     * 
     * @type {Array<string>}
     * @memberof CacheKeys200Response
     */
    keys?: Array<string>;
    /**
     * True if the result was capped at 10,000 keys
     * @type {boolean}
     * @memberof CacheKeys200Response
     */
    truncated?: boolean;
}

/**
 * Check if a given object implements the CacheKeys200Response interface.
 */
export function instanceOfCacheKeys200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CacheKeys200ResponseFromJSON(json: any): CacheKeys200Response {
    return CacheKeys200ResponseFromJSONTyped(json, false);
}

export function CacheKeys200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CacheKeys200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'keys': !exists(json, 'keys') ? undefined : json['keys'],
        'truncated': !exists(json, 'truncated') ? undefined : json['truncated'],
    };
}

export function CacheKeys200ResponseToJSON(value?: CacheKeys200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'keys': value.keys,
        'truncated': value.truncated,
    };
}

