/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CacheSetMany200Response
 */
export interface CacheSetMany200Response {
    /**
     * 
     * @type {boolean}
     * @memberof CacheSetMany200Response
     */
    success?: boolean;
    /**
     * Number of entries stored
     * @type {number}
     * @memberof CacheSetMany200Response
     */
    count?: number;
}

/**
 * Check if a given object implements the CacheSetMany200Response interface.
 */
export function instanceOfCacheSetMany200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CacheSetMany200ResponseFromJSON(json: any): CacheSetMany200Response {
    return CacheSetMany200ResponseFromJSONTyped(json, false);
}

export function CacheSetMany200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CacheSetMany200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'count': !exists(json, 'count') ? undefined : json['count'],
    };
}

export function CacheSetMany200ResponseToJSON(value?: CacheSetMany200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'count': value.count,
    };
}

