/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CacheExpireRequest
 */
export interface CacheExpireRequest {
    /**
     * 
     * @type {string}
     * @memberof CacheExpireRequest
     */
    key: string;
    /**
     * New TTL in seconds from now
     * @type {number}
     * @memberof CacheExpireRequest
     */
    ttl: number;
}

/**
 * Check if a given object implements the CacheExpireRequest interface.
 */
export function instanceOfCacheExpireRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "ttl" in value;

    return isInstance;
}

export function CacheExpireRequestFromJSON(json: any): CacheExpireRequest {
    return CacheExpireRequestFromJSONTyped(json, false);
}

export function CacheExpireRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CacheExpireRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
        'ttl': json['ttl'],
    };
}

export function CacheExpireRequestToJSON(value?: CacheExpireRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'ttl': value.ttl,
    };
}

