/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CacheGetRequest
 */
export interface CacheGetRequest {
    /**
     * 
     * @type {string}
     * @memberof CacheGetRequest
     */
    key: string;
}

/**
 * Check if a given object implements the CacheGetRequest interface.
 */
export function instanceOfCacheGetRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;

    return isInstance;
}

export function CacheGetRequestFromJSON(json: any): CacheGetRequest {
    return CacheGetRequestFromJSONTyped(json, false);
}

export function CacheGetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CacheGetRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
    };
}

export function CacheGetRequestToJSON(value?: CacheGetRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
    };
}

