/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CacheIncrementRequest
 */
export interface CacheIncrementRequest {
    /**
     * 
     * @type {string}
     * @memberof CacheIncrementRequest
     */
    key: string;
    /**
     * Amount to increment by (default 1, can be negative)
     * @type {number}
     * @memberof CacheIncrementRequest
     */
    amount?: number;
    /**
     * Starting value if key does not exist (default 0)
     * @type {number}
     * @memberof CacheIncrementRequest
     */
    initialValue?: number;
    /**
     * TTL in seconds for newly created keys
     * @type {number}
     * @memberof CacheIncrementRequest
     */
    ttl?: number;
}

/**
 * Check if a given object implements the CacheIncrementRequest interface.
 */
export function instanceOfCacheIncrementRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;

    return isInstance;
}

export function CacheIncrementRequestFromJSON(json: any): CacheIncrementRequest {
    return CacheIncrementRequestFromJSONTyped(json, false);
}

export function CacheIncrementRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CacheIncrementRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'initialValue': !exists(json, 'initialValue') ? undefined : json['initialValue'],
        'ttl': !exists(json, 'ttl') ? undefined : json['ttl'],
    };
}

export function CacheIncrementRequestToJSON(value?: CacheIncrementRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'amount': value.amount,
        'initialValue': value.initialValue,
        'ttl': value.ttl,
    };
}

