/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CacheGet200Response
 */
export interface CacheGet200Response {
    /**
     * 
     * @type {any}
     * @memberof CacheGet200Response
     */
    value?: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof CacheGet200Response
     */
    _exists?: boolean;
}

/**
 * Check if a given object implements the CacheGet200Response interface.
 */
export function instanceOfCacheGet200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CacheGet200ResponseFromJSON(json: any): CacheGet200Response {
    return CacheGet200ResponseFromJSONTyped(json, false);
}

export function CacheGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CacheGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': !exists(json, 'value') ? undefined : json['value'],
        '_exists': !exists(json, 'exists') ? undefined : json['exists'],
    };
}

export function CacheGet200ResponseToJSON(value?: CacheGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
        'exists': value._exists,
    };
}

