/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CacheSet200Response
 */
export interface CacheSet200Response {
    /**
     * 
     * @type {boolean}
     * @memberof CacheSet200Response
     */
    success?: boolean;
}

/**
 * Check if a given object implements the CacheSet200Response interface.
 */
export function instanceOfCacheSet200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CacheSet200ResponseFromJSON(json: any): CacheSet200Response {
    return CacheSet200ResponseFromJSONTyped(json, false);
}

export function CacheSet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CacheSet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
    };
}

export function CacheSet200ResponseToJSON(value?: CacheSet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
    };
}

