/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
import type { ChatMessage } from './ChatMessage.js';
import {
    ChatMessageFromJSON,
    ChatMessageFromJSONTyped,
    ChatMessageToJSON,
} from './ChatMessage.js';

/**
 * 
 * @export
 * @interface ChatCompletionResponseChoicesInner
 */
export interface ChatCompletionResponseChoicesInner {
    /**
     * 
     * @type {number}
     * @memberof ChatCompletionResponseChoicesInner
     */
    index?: number;
    /**
     * 
     * @type {ChatMessage}
     * @memberof ChatCompletionResponseChoicesInner
     */
    message?: ChatMessage;
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionResponseChoicesInner
     */
    finishReason?: ChatCompletionResponseChoicesInnerFinishReasonEnum;
}


/**
 * @export
 */
export const ChatCompletionResponseChoicesInnerFinishReasonEnum = {
    Stop: 'stop',
    Length: 'length',
    ContentFilter: 'content_filter'
} as const;
export type ChatCompletionResponseChoicesInnerFinishReasonEnum = typeof ChatCompletionResponseChoicesInnerFinishReasonEnum[keyof typeof ChatCompletionResponseChoicesInnerFinishReasonEnum];


/**
 * Check if a given object implements the ChatCompletionResponseChoicesInner interface.
 */
export function instanceOfChatCompletionResponseChoicesInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChatCompletionResponseChoicesInnerFromJSON(json: any): ChatCompletionResponseChoicesInner {
    return ChatCompletionResponseChoicesInnerFromJSONTyped(json, false);
}

export function ChatCompletionResponseChoicesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionResponseChoicesInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'index': !exists(json, 'index') ? undefined : json['index'],
        'message': !exists(json, 'message') ? undefined : ChatMessageFromJSON(json['message']),
        'finishReason': !exists(json, 'finish_reason') ? undefined : json['finish_reason'],
    };
}

export function ChatCompletionResponseChoicesInnerToJSON(value?: ChatCompletionResponseChoicesInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'index': value.index,
        'message': ChatMessageToJSON(value.message),
        'finish_reason': value.finishReason,
    };
}

