/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
import type { ChatCompletionRequestStreamOptions } from './ChatCompletionRequestStreamOptions.js';
import {
    ChatCompletionRequestStreamOptionsFromJSON,
    ChatCompletionRequestStreamOptionsFromJSONTyped,
    ChatCompletionRequestStreamOptionsToJSON,
} from './ChatCompletionRequestStreamOptions.js';
import type { ChatMessage } from './ChatMessage.js';
import {
    ChatMessageFromJSON,
    ChatMessageFromJSONTyped,
    ChatMessageToJSON,
} from './ChatMessage.js';

/**
 * 
 * @export
 * @interface ChatCompletionRequest
 */
export interface ChatCompletionRequest {
    /**
     * Model identifier (provider-specific)
     * @type {string}
     * @memberof ChatCompletionRequest
     */
    model?: string;
    /**
     * 
     * @type {Array<ChatMessage>}
     * @memberof ChatCompletionRequest
     */
    messages: Array<ChatMessage>;
    /**
     * When true, returns a server-sent events (SSE) stream of token
     * deltas. Each event is `data: <json>\n\n`. The stream ends with
     * `data: [DONE]\n\n`.
     * 
     * @type {boolean}
     * @memberof ChatCompletionRequest
     */
    stream?: boolean;
    /**
     * 
     * @type {ChatCompletionRequestStreamOptions}
     * @memberof ChatCompletionRequest
     */
    streamOptions?: ChatCompletionRequestStreamOptions;
    /**
     * Sampling temperature (0=deterministic, 2=creative)
     * @type {number}
     * @memberof ChatCompletionRequest
     */
    temperature?: number;
    /**
     * Maximum tokens to generate
     * @type {number}
     * @memberof ChatCompletionRequest
     */
    maxTokens?: number;
    /**
     * Nucleus sampling probability
     * @type {number}
     * @memberof ChatCompletionRequest
     */
    topP?: number;
}

/**
 * Check if a given object implements the ChatCompletionRequest interface.
 */
export function instanceOfChatCompletionRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "messages" in value;

    return isInstance;
}

export function ChatCompletionRequestFromJSON(json: any): ChatCompletionRequest {
    return ChatCompletionRequestFromJSONTyped(json, false);
}

export function ChatCompletionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'model': !exists(json, 'model') ? undefined : json['model'],
        'messages': ((json['messages'] as Array<any>).map(ChatMessageFromJSON)),
        'stream': !exists(json, 'stream') ? undefined : json['stream'],
        'streamOptions': !exists(json, 'stream_options') ? undefined : ChatCompletionRequestStreamOptionsFromJSON(json['stream_options']),
        'temperature': !exists(json, 'temperature') ? undefined : json['temperature'],
        'maxTokens': !exists(json, 'max_tokens') ? undefined : json['max_tokens'],
        'topP': !exists(json, 'top_p') ? undefined : json['top_p'],
    };
}

export function ChatCompletionRequestToJSON(value?: ChatCompletionRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'model': value.model,
        'messages': ((value.messages as Array<any>).map(ChatMessageToJSON)),
        'stream': value.stream,
        'stream_options': ChatCompletionRequestStreamOptionsToJSON(value.streamOptions),
        'temperature': value.temperature,
        'max_tokens': value.maxTokens,
        'top_p': value.topP,
    };
}

