/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ChatCompletionRequestStreamOptions
 */
export interface ChatCompletionRequestStreamOptions {
    /**
     * Include token usage in the final SSE frame when streaming.
     * The last data frame before [DONE] will contain a `usage` object.
     * 
     * @type {boolean}
     * @memberof ChatCompletionRequestStreamOptions
     */
    includeUsage?: boolean;
}

/**
 * Check if a given object implements the ChatCompletionRequestStreamOptions interface.
 */
export function instanceOfChatCompletionRequestStreamOptions(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChatCompletionRequestStreamOptionsFromJSON(json: any): ChatCompletionRequestStreamOptions {
    return ChatCompletionRequestStreamOptionsFromJSONTyped(json, false);
}

export function ChatCompletionRequestStreamOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionRequestStreamOptions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'includeUsage': !exists(json, 'include_usage') ? undefined : json['include_usage'],
    };
}

export function ChatCompletionRequestStreamOptionsToJSON(value?: ChatCompletionRequestStreamOptions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'include_usage': value.includeUsage,
    };
}

