/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
import type { ChatCompletionResponseChoicesInner } from './ChatCompletionResponseChoicesInner.js';
import {
    ChatCompletionResponseChoicesInnerFromJSON,
    ChatCompletionResponseChoicesInnerFromJSONTyped,
    ChatCompletionResponseChoicesInnerToJSON,
} from './ChatCompletionResponseChoicesInner.js';
import type { TokenUsage } from './TokenUsage.js';
import {
    TokenUsageFromJSON,
    TokenUsageFromJSONTyped,
    TokenUsageToJSON,
} from './TokenUsage.js';

/**
 * 
 * @export
 * @interface ChatCompletionResponse
 */
export interface ChatCompletionResponse {
    /**
     * Unique completion ID
     * @type {string}
     * @memberof ChatCompletionResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionResponse
     */
    object?: ChatCompletionResponseObjectEnum;
    /**
     * Unix timestamp
     * @type {number}
     * @memberof ChatCompletionResponse
     */
    created?: number;
    /**
     * Model used for completion
     * @type {string}
     * @memberof ChatCompletionResponse
     */
    model?: string;
    /**
     * 
     * @type {Array<ChatCompletionResponseChoicesInner>}
     * @memberof ChatCompletionResponse
     */
    choices?: Array<ChatCompletionResponseChoicesInner>;
    /**
     * 
     * @type {TokenUsage}
     * @memberof ChatCompletionResponse
     */
    usage?: TokenUsage;
}


/**
 * @export
 */
export const ChatCompletionResponseObjectEnum = {
    ChatCompletion: 'chat.completion'
} as const;
export type ChatCompletionResponseObjectEnum = typeof ChatCompletionResponseObjectEnum[keyof typeof ChatCompletionResponseObjectEnum];


/**
 * Check if a given object implements the ChatCompletionResponse interface.
 */
export function instanceOfChatCompletionResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChatCompletionResponseFromJSON(json: any): ChatCompletionResponse {
    return ChatCompletionResponseFromJSONTyped(json, false);
}

export function ChatCompletionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'object': !exists(json, 'object') ? undefined : json['object'],
        'created': !exists(json, 'created') ? undefined : json['created'],
        'model': !exists(json, 'model') ? undefined : json['model'],
        'choices': !exists(json, 'choices') ? undefined : ((json['choices'] as Array<any>).map(ChatCompletionResponseChoicesInnerFromJSON)),
        'usage': !exists(json, 'usage') ? undefined : TokenUsageFromJSON(json['usage']),
    };
}

export function ChatCompletionResponseToJSON(value?: ChatCompletionResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'object': value.object,
        'created': value.created,
        'model': value.model,
        'choices': value.choices === undefined ? undefined : ((value.choices as Array<any>).map(ChatCompletionResponseChoicesInnerToJSON)),
        'usage': TokenUsageToJSON(value.usage),
    };
}

