/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ConfigureRequest
 */
export interface ConfigureRequest {
    /**
     * 
     * @type {string}
     * @memberof ConfigureRequest
     */
    embeddingModel: ConfigureRequestEmbeddingModelEnum;
}


/**
 * @export
 */
export const ConfigureRequestEmbeddingModelEnum = {
    English: 'english',
    Multilingual: 'multilingual'
} as const;
export type ConfigureRequestEmbeddingModelEnum = typeof ConfigureRequestEmbeddingModelEnum[keyof typeof ConfigureRequestEmbeddingModelEnum];


/**
 * Check if a given object implements the ConfigureRequest interface.
 */
export function instanceOfConfigureRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "embeddingModel" in value;

    return isInstance;
}

export function ConfigureRequestFromJSON(json: any): ConfigureRequest {
    return ConfigureRequestFromJSONTyped(json, false);
}

export function ConfigureRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigureRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'embeddingModel': json['embeddingModel'],
    };
}

export function ConfigureRequestToJSON(value?: ConfigureRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'embeddingModel': value.embeddingModel,
    };
}

