/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
import type { DbBatchResultResultsInner } from './DbBatchResultResultsInner.js';
import {
    DbBatchResultResultsInnerFromJSON,
    DbBatchResultResultsInnerFromJSONTyped,
    DbBatchResultResultsInnerToJSON,
} from './DbBatchResultResultsInner.js';

/**
 * 
 * @export
 * @interface DbBatchResult
 */
export interface DbBatchResult {
    /**
     * One entry per query, in request order
     * @type {Array<DbBatchResultResultsInner>}
     * @memberof DbBatchResult
     */
    results?: Array<DbBatchResultResultsInner>;
    /**
     * True only if ALL queries succeeded
     * @type {boolean}
     * @memberof DbBatchResult
     */
    success?: boolean;
}

/**
 * Check if a given object implements the DbBatchResult interface.
 */
export function instanceOfDbBatchResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DbBatchResultFromJSON(json: any): DbBatchResult {
    return DbBatchResultFromJSONTyped(json, false);
}

export function DbBatchResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): DbBatchResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(DbBatchResultResultsInnerFromJSON)),
        'success': !exists(json, 'success') ? undefined : json['success'],
    };
}

export function DbBatchResultToJSON(value?: DbBatchResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(DbBatchResultResultsInnerToJSON)),
        'success': value.success,
    };
}

