/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
import type { DbBatchRequestQueriesInner } from './DbBatchRequestQueriesInner.js';
import {
    DbBatchRequestQueriesInnerFromJSON,
    DbBatchRequestQueriesInnerFromJSONTyped,
    DbBatchRequestQueriesInnerToJSON,
} from './DbBatchRequestQueriesInner.js';

/**
 * 
 * @export
 * @interface DbBatchRequest
 */
export interface DbBatchRequest {
    /**
     * Array of queries to execute (max 25)
     * @type {Array<DbBatchRequestQueriesInner>}
     * @memberof DbBatchRequest
     */
    queries: Array<DbBatchRequestQueriesInner>;
}

/**
 * Check if a given object implements the DbBatchRequest interface.
 */
export function instanceOfDbBatchRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "queries" in value;

    return isInstance;
}

export function DbBatchRequestFromJSON(json: any): DbBatchRequest {
    return DbBatchRequestFromJSONTyped(json, false);
}

export function DbBatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DbBatchRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'queries': ((json['queries'] as Array<any>).map(DbBatchRequestQueriesInnerFromJSON)),
    };
}

export function DbBatchRequestToJSON(value?: DbBatchRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'queries': ((value.queries as Array<any>).map(DbBatchRequestQueriesInnerToJSON)),
    };
}

