/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface DbBatchResultResultsInner
 */
export interface DbBatchResultResultsInner {
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof DbBatchResultResultsInner
     */
    results?: Array<{ [key: string]: any; }>;
    /**
     * 
     * @type {boolean}
     * @memberof DbBatchResultResultsInner
     */
    success?: boolean;
    /**
     * Error message if this query failed
     * @type {string}
     * @memberof DbBatchResultResultsInner
     */
    error?: string;
}

/**
 * Check if a given object implements the DbBatchResultResultsInner interface.
 */
export function instanceOfDbBatchResultResultsInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DbBatchResultResultsInnerFromJSON(json: any): DbBatchResultResultsInner {
    return DbBatchResultResultsInnerFromJSONTyped(json, false);
}

export function DbBatchResultResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): DbBatchResultResultsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'results': !exists(json, 'results') ? undefined : json['results'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'error': !exists(json, 'error') ? undefined : json['error'],
    };
}

export function DbBatchResultResultsInnerToJSON(value?: DbBatchResultResultsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'results': value.results,
        'success': value.success,
        'error': value.error,
    };
}

