/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface DbQueryResult
 */
export interface DbQueryResult {
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof DbQueryResult
     */
    results?: Array<{ [key: string]: any; }>;
    /**
     * 
     * @type {number}
     * @memberof DbQueryResult
     */
    count?: number;
}

/**
 * Check if a given object implements the DbQueryResult interface.
 */
export function instanceOfDbQueryResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DbQueryResultFromJSON(json: any): DbQueryResult {
    return DbQueryResultFromJSONTyped(json, false);
}

export function DbQueryResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): DbQueryResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'results': !exists(json, 'results') ? undefined : json['results'],
        'count': !exists(json, 'count') ? undefined : json['count'],
    };
}

export function DbQueryResultToJSON(value?: DbQueryResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'results': value.results,
        'count': value.count,
    };
}

