/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface DbQueryRequest
 */
export interface DbQueryRequest {
    /**
     * SQL query to execute
     * @type {string}
     * @memberof DbQueryRequest
     */
    sql: string;
    /**
     * Query parameters for prepared statements
     * @type {Array<any>}
     * @memberof DbQueryRequest
     */
    params?: Array<any>;
}

/**
 * Check if a given object implements the DbQueryRequest interface.
 */
export function instanceOfDbQueryRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "sql" in value;

    return isInstance;
}

export function DbQueryRequestFromJSON(json: any): DbQueryRequest {
    return DbQueryRequestFromJSONTyped(json, false);
}

export function DbQueryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DbQueryRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sql': json['sql'],
        'params': !exists(json, 'params') ? undefined : json['params'],
    };
}

export function DbQueryRequestToJSON(value?: DbQueryRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sql': value.sql,
        'params': value.params,
    };
}

