/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface DeleteRequest
 */
export interface DeleteRequest {
    /**
     * 
     * @type {string}
     * @memberof DeleteRequest
     */
    id: string;
}

/**
 * Check if a given object implements the DeleteRequest interface.
 */
export function instanceOfDeleteRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function DeleteRequestFromJSON(json: any): DeleteRequest {
    return DeleteRequestFromJSONTyped(json, false);
}

export function DeleteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function DeleteRequestToJSON(value?: DeleteRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

