/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface DeleteByTypeRequest
 */
export interface DeleteByTypeRequest {
    /**
     * 
     * @type {string}
     * @memberof DeleteByTypeRequest
     */
    type: string;
}

/**
 * Check if a given object implements the DeleteByTypeRequest interface.
 */
export function instanceOfDeleteByTypeRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function DeleteByTypeRequestFromJSON(json: any): DeleteByTypeRequest {
    return DeleteByTypeRequestFromJSONTyped(json, false);
}

export function DeleteByTypeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteByTypeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function DeleteByTypeRequestToJSON(value?: DeleteByTypeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
    };
}

