/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface GatewayBillingLogRequest
 */
export interface GatewayBillingLogRequest {
    /**
     * The Consumer ID making the request
     * @type {string}
     * @memberof GatewayBillingLogRequest
     */
    consumerId: string;
    /**
     * The Developer Gateway API ID being consumed
     * @type {string}
     * @memberof GatewayBillingLogRequest
     */
    apiId: string;
    /**
     * Optional metric name (default: 'units')
     * @type {string}
     * @memberof GatewayBillingLogRequest
     */
    metric?: string;
    /**
     * Amount of usage to log
     * @type {number}
     * @memberof GatewayBillingLogRequest
     */
    units: number;
}

/**
 * Check if a given object implements the GatewayBillingLogRequest interface.
 */
export function instanceOfGatewayBillingLogRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "consumerId" in value;
    isInstance = isInstance && "apiId" in value;
    isInstance = isInstance && "units" in value;

    return isInstance;
}

export function GatewayBillingLogRequestFromJSON(json: any): GatewayBillingLogRequest {
    return GatewayBillingLogRequestFromJSONTyped(json, false);
}

export function GatewayBillingLogRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayBillingLogRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'consumerId': json['consumerId'],
        'apiId': json['apiId'],
        'metric': !exists(json, 'metric') ? undefined : json['metric'],
        'units': json['units'],
    };
}

export function GatewayBillingLogRequestToJSON(value?: GatewayBillingLogRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'consumerId': value.consumerId,
        'apiId': value.apiId,
        'metric': value.metric,
        'units': value.units,
    };
}

