/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface GatewayBillingLog200Response
 */
export interface GatewayBillingLog200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GatewayBillingLog200Response
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GatewayBillingLog200Response
     */
    loggedUnits?: number;
}

/**
 * Check if a given object implements the GatewayBillingLog200Response interface.
 */
export function instanceOfGatewayBillingLog200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GatewayBillingLog200ResponseFromJSON(json: any): GatewayBillingLog200Response {
    return GatewayBillingLog200ResponseFromJSONTyped(json, false);
}

export function GatewayBillingLog200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayBillingLog200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'loggedUnits': !exists(json, 'loggedUnits') ? undefined : json['loggedUnits'],
    };
}

export function GatewayBillingLog200ResponseToJSON(value?: GatewayBillingLog200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'loggedUnits': value.loggedUnits,
    };
}

