/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
import type { TokenWallet } from './TokenWallet.js';
import {
    TokenWalletFromJSON,
    TokenWalletFromJSONTyped,
    TokenWalletToJSON,
} from './TokenWallet.js';

/**
 * 
 * @export
 * @interface GatewayGetWallet200Response
 */
export interface GatewayGetWallet200Response {
    /**
     * 
     * @type {TokenWallet}
     * @memberof GatewayGetWallet200Response
     */
    wallet?: TokenWallet;
}

/**
 * Check if a given object implements the GatewayGetWallet200Response interface.
 */
export function instanceOfGatewayGetWallet200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GatewayGetWallet200ResponseFromJSON(json: any): GatewayGetWallet200Response {
    return GatewayGetWallet200ResponseFromJSONTyped(json, false);
}

export function GatewayGetWallet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayGetWallet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'wallet': !exists(json, 'wallet') ? undefined : TokenWalletFromJSON(json['wallet']),
    };
}

export function GatewayGetWallet200ResponseToJSON(value?: GatewayGetWallet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'wallet': TokenWalletToJSON(value.wallet),
    };
}

