/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface IngestRequest
 */
export interface IngestRequest {
    /**
     * Text content to index
     * @type {string}
     * @memberof IngestRequest
     */
    content: string;
    /**
     * Optional custom ID
     * @type {string}
     * @memberof IngestRequest
     */
    id?: string;
    /**
     * Category/type of content
     * @type {string}
     * @memberof IngestRequest
     */
    type: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof IngestRequest
     */
    metadata?: { [key: string]: any; } | null;
}

/**
 * Check if a given object implements the IngestRequest interface.
 */
export function instanceOfIngestRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "content" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function IngestRequestFromJSON(json: any): IngestRequest {
    return IngestRequestFromJSONTyped(json, false);
}

export function IngestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngestRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'content': json['content'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'type': json['type'],
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
    };
}

export function IngestRequestToJSON(value?: IngestRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'content': value.content,
        'id': value.id,
        'type': value.type,
        'metadata': value.metadata,
    };
}

