/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface JobRecord
 */
export interface JobRecord {
    /**
     * Unique job ID
     * @type {string}
     * @memberof JobRecord
     */
    id?: string;
    /**
     * Job type (e.g. "send-email")
     * @type {string}
     * @memberof JobRecord
     */
    type?: string;
    /**
     * Job payload
     * @type {{ [key: string]: any; }}
     * @memberof JobRecord
     */
    data?: { [key: string]: any; } | null;
    /**
     * 
     * @type {string}
     * @memberof JobRecord
     */
    status?: JobRecordStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof JobRecord
     */
    projectId?: string;
    /**
     * 
     * @type {Date}
     * @memberof JobRecord
     */
    createdAt?: Date;
}


/**
 * @export
 */
export const JobRecordStatusEnum = {
    Queued: 'queued',
    Processing: 'processing',
    Completed: 'completed',
    Failed: 'failed',
    Cancelled: 'cancelled'
} as const;
export type JobRecordStatusEnum = typeof JobRecordStatusEnum[keyof typeof JobRecordStatusEnum];


/**
 * Check if a given object implements the JobRecord interface.
 */
export function instanceOfJobRecord(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function JobRecordFromJSON(json: any): JobRecord {
    return JobRecordFromJSONTyped(json, false);
}

export function JobRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobRecord {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'data': !exists(json, 'data') ? undefined : json['data'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'projectId': !exists(json, 'projectId') ? undefined : json['projectId'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
    };
}

export function JobRecordToJSON(value?: JobRecord | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': value.type,
        'data': value.data,
        'status': value.status,
        'projectId': value.projectId,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
    };
}

