/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
import type { TypeStats } from './TypeStats.js';
import {
    TypeStatsFromJSON,
    TypeStatsFromJSONTyped,
    TypeStatsToJSON,
} from './TypeStats.js';

/**
 * 
 * @export
 * @interface ListTypes200Response
 */
export interface ListTypes200Response {
    /**
     * 
     * @type {Array<TypeStats>}
     * @memberof ListTypes200Response
     */
    types?: Array<TypeStats>;
}

/**
 * Check if a given object implements the ListTypes200Response interface.
 */
export function instanceOfListTypes200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListTypes200ResponseFromJSON(json: any): ListTypes200Response {
    return ListTypes200ResponseFromJSONTyped(json, false);
}

export function ListTypes200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTypes200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'types': !exists(json, 'types') ? undefined : ((json['types'] as Array<any>).map(TypeStatsFromJSON)),
    };
}

export function ListTypes200ResponseToJSON(value?: ListTypes200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'types': value.types === undefined ? undefined : ((value.types as Array<any>).map(TypeStatsToJSON)),
    };
}

