/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface QueryRequest
 */
export interface QueryRequest {
    /**
     * 
     * @type {string}
     * @memberof QueryRequest
     */
    text: string;
    /**
     * 
     * @type {number}
     * @memberof QueryRequest
     */
    topK?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof QueryRequest
     */
    types?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof QueryRequest
     */
    filter?: { [key: string]: any; } | null;
}

/**
 * Check if a given object implements the QueryRequest interface.
 */
export function instanceOfQueryRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "text" in value;

    return isInstance;
}

export function QueryRequestFromJSON(json: any): QueryRequest {
    return QueryRequestFromJSONTyped(json, false);
}

export function QueryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'text': json['text'],
        'topK': !exists(json, 'topK') ? undefined : json['topK'],
        'types': !exists(json, 'types') ? undefined : json['types'],
        'filter': !exists(json, 'filter') ? undefined : json['filter'],
    };
}

export function QueryRequestToJSON(value?: QueryRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'text': value.text,
        'topK': value.topK,
        'types': value.types,
        'filter': value.filter,
    };
}

