/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
import type { SearchResult } from './SearchResult.js';
import {
    SearchResultFromJSON,
    SearchResultFromJSONTyped,
    SearchResultToJSON,
} from './SearchResult.js';

/**
 * 
 * @export
 * @interface Query200Response
 */
export interface Query200Response {
    /**
     * 
     * @type {Array<SearchResult>}
     * @memberof Query200Response
     */
    results?: Array<SearchResult>;
}

/**
 * Check if a given object implements the Query200Response interface.
 */
export function instanceOfQuery200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Query200ResponseFromJSON(json: any): Query200Response {
    return Query200ResponseFromJSONTyped(json, false);
}

export function Query200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Query200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(SearchResultFromJSON)),
    };
}

export function Query200ResponseToJSON(value?: Query200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(SearchResultToJSON)),
    };
}

