/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface QueueEnqueue201Response
 */
export interface QueueEnqueue201Response {
    /**
     * 
     * @type {string}
     * @memberof QueueEnqueue201Response
     */
    jobId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof QueueEnqueue201Response
     */
    success?: boolean;
}

/**
 * Check if a given object implements the QueueEnqueue201Response interface.
 */
export function instanceOfQueueEnqueue201Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function QueueEnqueue201ResponseFromJSON(json: any): QueueEnqueue201Response {
    return QueueEnqueue201ResponseFromJSONTyped(json, false);
}

export function QueueEnqueue201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueueEnqueue201Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jobId': !exists(json, 'jobId') ? undefined : json['jobId'],
        'success': !exists(json, 'success') ? undefined : json['success'],
    };
}

export function QueueEnqueue201ResponseToJSON(value?: QueueEnqueue201Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jobId': value.jobId,
        'success': value.success,
    };
}

