/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
import type { JobRecord } from './JobRecord.js';
import {
    JobRecordFromJSON,
    JobRecordFromJSONTyped,
    JobRecordToJSON,
} from './JobRecord.js';

/**
 * 
 * @export
 * @interface QueueListJobs200Response
 */
export interface QueueListJobs200Response {
    /**
     * 
     * @type {Array<JobRecord>}
     * @memberof QueueListJobs200Response
     */
    jobs?: Array<JobRecord>;
    /**
     * 
     * @type {boolean}
     * @memberof QueueListJobs200Response
     */
    listComplete?: boolean;
    /**
     * 
     * @type {string}
     * @memberof QueueListJobs200Response
     */
    cursor?: string;
}

/**
 * Check if a given object implements the QueueListJobs200Response interface.
 */
export function instanceOfQueueListJobs200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function QueueListJobs200ResponseFromJSON(json: any): QueueListJobs200Response {
    return QueueListJobs200ResponseFromJSONTyped(json, false);
}

export function QueueListJobs200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueueListJobs200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jobs': !exists(json, 'jobs') ? undefined : ((json['jobs'] as Array<any>).map(JobRecordFromJSON)),
        'listComplete': !exists(json, 'list_complete') ? undefined : json['list_complete'],
        'cursor': !exists(json, 'cursor') ? undefined : json['cursor'],
    };
}

export function QueueListJobs200ResponseToJSON(value?: QueueListJobs200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jobs': value.jobs === undefined ? undefined : ((value.jobs as Array<any>).map(JobRecordToJSON)),
        'list_complete': value.listComplete,
        'cursor': value.cursor,
    };
}

