/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface QueueListJobsRequest
 */
export interface QueueListJobsRequest {
    /**
     * Filter by job status
     * @type {string}
     * @memberof QueueListJobsRequest
     */
    status?: QueueListJobsRequestStatusEnum;
    /**
     * Filter by job type
     * @type {string}
     * @memberof QueueListJobsRequest
     */
    type?: string;
    /**
     * 
     * @type {number}
     * @memberof QueueListJobsRequest
     */
    limit?: number;
    /**
     * Pagination cursor from previous response
     * @type {string}
     * @memberof QueueListJobsRequest
     */
    cursor?: string;
}


/**
 * @export
 */
export const QueueListJobsRequestStatusEnum = {
    Queued: 'queued',
    Processing: 'processing',
    Completed: 'completed',
    Failed: 'failed',
    Cancelled: 'cancelled'
} as const;
export type QueueListJobsRequestStatusEnum = typeof QueueListJobsRequestStatusEnum[keyof typeof QueueListJobsRequestStatusEnum];


/**
 * Check if a given object implements the QueueListJobsRequest interface.
 */
export function instanceOfQueueListJobsRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function QueueListJobsRequestFromJSON(json: any): QueueListJobsRequest {
    return QueueListJobsRequestFromJSONTyped(json, false);
}

export function QueueListJobsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueueListJobsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : json['status'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'cursor': !exists(json, 'cursor') ? undefined : json['cursor'],
    };
}

export function QueueListJobsRequestToJSON(value?: QueueListJobsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'type': value.type,
        'limit': value.limit,
        'cursor': value.cursor,
    };
}

