/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface QueueGetJobRequest
 */
export interface QueueGetJobRequest {
    /**
     * 
     * @type {string}
     * @memberof QueueGetJobRequest
     */
    jobId: string;
}

/**
 * Check if a given object implements the QueueGetJobRequest interface.
 */
export function instanceOfQueueGetJobRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "jobId" in value;

    return isInstance;
}

export function QueueGetJobRequestFromJSON(json: any): QueueGetJobRequest {
    return QueueGetJobRequestFromJSONTyped(json, false);
}

export function QueueGetJobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueueGetJobRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jobId': json['jobId'],
    };
}

export function QueueGetJobRequestToJSON(value?: QueueGetJobRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jobId': value.jobId,
    };
}

