/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
import type { JobRecord } from './JobRecord.js';
import {
    JobRecordFromJSON,
    JobRecordFromJSONTyped,
    JobRecordToJSON,
} from './JobRecord.js';

/**
 * 
 * @export
 * @interface QueueGetJob200Response
 */
export interface QueueGetJob200Response {
    /**
     * 
     * @type {JobRecord}
     * @memberof QueueGetJob200Response
     */
    job?: JobRecord | null;
    /**
     * 
     * @type {boolean}
     * @memberof QueueGetJob200Response
     */
    _exists?: boolean;
}

/**
 * Check if a given object implements the QueueGetJob200Response interface.
 */
export function instanceOfQueueGetJob200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function QueueGetJob200ResponseFromJSON(json: any): QueueGetJob200Response {
    return QueueGetJob200ResponseFromJSONTyped(json, false);
}

export function QueueGetJob200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueueGetJob200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'job': !exists(json, 'job') ? undefined : JobRecordFromJSON(json['job']),
        '_exists': !exists(json, 'exists') ? undefined : json['exists'],
    };
}

export function QueueGetJob200ResponseToJSON(value?: QueueGetJob200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'job': JobRecordToJSON(value.job),
        'exists': value._exists,
    };
}

