/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface QueueEnqueueRequest
 */
export interface QueueEnqueueRequest {
    /**
     * 
     * @type {string}
     * @memberof QueueEnqueueRequest
     */
    type: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof QueueEnqueueRequest
     */
    data: { [key: string]: any; } | null;
    /**
     * Delay in seconds before processing
     * @type {number}
     * @memberof QueueEnqueueRequest
     */
    delay?: number;
}

/**
 * Check if a given object implements the QueueEnqueueRequest interface.
 */
export function instanceOfQueueEnqueueRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function QueueEnqueueRequestFromJSON(json: any): QueueEnqueueRequest {
    return QueueEnqueueRequestFromJSONTyped(json, false);
}

export function QueueEnqueueRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueueEnqueueRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'data': json['data'],
        'delay': !exists(json, 'delay') ? undefined : json['delay'],
    };
}

export function QueueEnqueueRequestToJSON(value?: QueueEnqueueRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'data': value.data,
        'delay': value.delay,
    };
}

