/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface QueueCancelJob200Response
 */
export interface QueueCancelJob200Response {
    /**
     * 
     * @type {boolean}
     * @memberof QueueCancelJob200Response
     */
    success?: boolean;
    /**
     * Optional advisory note (e.g. already in terminal state)
     * @type {string}
     * @memberof QueueCancelJob200Response
     */
    note?: string;
}

/**
 * Check if a given object implements the QueueCancelJob200Response interface.
 */
export function instanceOfQueueCancelJob200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function QueueCancelJob200ResponseFromJSON(json: any): QueueCancelJob200Response {
    return QueueCancelJob200ResponseFromJSONTyped(json, false);
}

export function QueueCancelJob200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueueCancelJob200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'note': !exists(json, 'note') ? undefined : json['note'],
    };
}

export function QueueCancelJob200ResponseToJSON(value?: QueueCancelJob200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'note': value.note,
    };
}

