/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SearchGetRequest
 */
export interface SearchGetRequest {
    /**
     * ID of the item to retrieve
     * @type {string}
     * @memberof SearchGetRequest
     */
    id: string;
}

/**
 * Check if a given object implements the SearchGetRequest interface.
 */
export function instanceOfSearchGetRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function SearchGetRequestFromJSON(json: any): SearchGetRequest {
    return SearchGetRequestFromJSONTyped(json, false);
}

export function SearchGetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchGetRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function SearchGetRequestToJSON(value?: SearchGetRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

