/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SearchUpdateRequest
 */
export interface SearchUpdateRequest {
    /**
     * ID of the item to update
     * @type {string}
     * @memberof SearchUpdateRequest
     */
    id: string;
    /**
     * New text content to re-embed
     * @type {string}
     * @memberof SearchUpdateRequest
     */
    content: string;
    /**
     * New type (replaces existing type)
     * @type {string}
     * @memberof SearchUpdateRequest
     */
    type?: string;
    /**
     * New metadata (replaces existing metadata)
     * @type {{ [key: string]: any; }}
     * @memberof SearchUpdateRequest
     */
    metadata?: { [key: string]: any; } | null;
}

/**
 * Check if a given object implements the SearchUpdateRequest interface.
 */
export function instanceOfSearchUpdateRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "content" in value;

    return isInstance;
}

export function SearchUpdateRequestFromJSON(json: any): SearchUpdateRequest {
    return SearchUpdateRequestFromJSONTyped(json, false);
}

export function SearchUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchUpdateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'content': json['content'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
    };
}

export function SearchUpdateRequestToJSON(value?: SearchUpdateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'content': value.content,
        'type': value.type,
        'metadata': value.metadata,
    };
}

