/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
import type { SearchResult } from './SearchResult.js';
import {
    SearchResultFromJSON,
    SearchResultFromJSONTyped,
    SearchResultToJSON,
} from './SearchResult.js';

/**
 * 
 * @export
 * @interface SearchGet200Response
 */
export interface SearchGet200Response {
    /**
     * 
     * @type {SearchResult}
     * @memberof SearchGet200Response
     */
    result?: SearchResult | null;
    /**
     * 
     * @type {boolean}
     * @memberof SearchGet200Response
     */
    _exists?: boolean;
}

/**
 * Check if a given object implements the SearchGet200Response interface.
 */
export function instanceOfSearchGet200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SearchGet200ResponseFromJSON(json: any): SearchGet200Response {
    return SearchGet200ResponseFromJSONTyped(json, false);
}

export function SearchGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : SearchResultFromJSON(json['result']),
        '_exists': !exists(json, 'exists') ? undefined : json['exists'],
    };
}

export function SearchGet200ResponseToJSON(value?: SearchGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': SearchResultToJSON(value.result),
        'exists': value._exists,
    };
}

