/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SearchCountRequest
 */
export interface SearchCountRequest {
    /**
     * Filter count by type (omit for total count)
     * @type {string}
     * @memberof SearchCountRequest
     */
    type?: string;
}

/**
 * Check if a given object implements the SearchCountRequest interface.
 */
export function instanceOfSearchCountRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SearchCountRequestFromJSON(json: any): SearchCountRequest {
    return SearchCountRequestFromJSONTyped(json, false);
}

export function SearchCountRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchCountRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function SearchCountRequestToJSON(value?: SearchCountRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
    };
}

