/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SearchResult
 */
export interface SearchResult {
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    content?: string;
    /**
     * 
     * @type {number}
     * @memberof SearchResult
     */
    score?: number;
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    type?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof SearchResult
     */
    metadata?: { [key: string]: any; } | null;
}

/**
 * Check if a given object implements the SearchResult interface.
 */
export function instanceOfSearchResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SearchResultFromJSON(json: any): SearchResult {
    return SearchResultFromJSONTyped(json, false);
}

export function SearchResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'score': !exists(json, 'score') ? undefined : json['score'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
    };
}

export function SearchResultToJSON(value?: SearchResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'content': value.content,
        'score': value.score,
        'type': value.type,
        'metadata': value.metadata,
    };
}

