/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SearchCount200Response
 */
export interface SearchCount200Response {
    /**
     * 
     * @type {number}
     * @memberof SearchCount200Response
     */
    count?: number;
}

/**
 * Check if a given object implements the SearchCount200Response interface.
 */
export function instanceOfSearchCount200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SearchCount200ResponseFromJSON(json: any): SearchCount200Response {
    return SearchCount200ResponseFromJSONTyped(json, false);
}

export function SearchCount200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchCount200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
    };
}

export function SearchCount200ResponseToJSON(value?: SearchCount200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
    };
}

