/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ServicesInvokeRequest
 */
export interface ServicesInvokeRequest {
    /**
     * 
     * @type {string}
     * @memberof ServicesInvokeRequest
     */
    serviceName: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ServicesInvokeRequest
     */
    data: { [key: string]: any; } | null;
}

/**
 * Check if a given object implements the ServicesInvokeRequest interface.
 */
export function instanceOfServicesInvokeRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "serviceName" in value;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function ServicesInvokeRequestFromJSON(json: any): ServicesInvokeRequest {
    return ServicesInvokeRequestFromJSONTyped(json, false);
}

export function ServicesInvokeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServicesInvokeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'serviceName': json['serviceName'],
        'data': json['data'],
    };
}

export function ServicesInvokeRequestToJSON(value?: ServicesInvokeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'serviceName': value.serviceName,
        'data': value.data,
    };
}

