/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ServicesInvoke200Response
 */
export interface ServicesInvoke200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ServicesInvoke200Response
     */
    success?: boolean;
    /**
     * 
     * @type {any}
     * @memberof ServicesInvoke200Response
     */
    result?: any | null;
}

/**
 * Check if a given object implements the ServicesInvoke200Response interface.
 */
export function instanceOfServicesInvoke200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ServicesInvoke200ResponseFromJSON(json: any): ServicesInvoke200Response {
    return ServicesInvoke200ResponseFromJSONTyped(json, false);
}

export function ServicesInvoke200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServicesInvoke200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'result': !exists(json, 'result') ? undefined : json['result'],
    };
}

export function ServicesInvoke200ResponseToJSON(value?: ServicesInvoke200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'result': value.result,
    };
}

