/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface StorageExists200Response
 */
export interface StorageExists200Response {
    /**
     * 
     * @type {boolean}
     * @memberof StorageExists200Response
     */
    _exists?: boolean;
}

/**
 * Check if a given object implements the StorageExists200Response interface.
 */
export function instanceOfStorageExists200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageExists200ResponseFromJSON(json: any): StorageExists200Response {
    return StorageExists200ResponseFromJSONTyped(json, false);
}

export function StorageExists200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageExists200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        '_exists': !exists(json, 'exists') ? undefined : json['exists'],
    };
}

export function StorageExists200ResponseToJSON(value?: StorageExists200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'exists': value._exists,
    };
}

