/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface StorageListRequest
 */
export interface StorageListRequest {
    /**
     * Key prefix to filter by
     * @type {string}
     * @memberof StorageListRequest
     */
    prefix?: string;
    /**
     * 
     * @type {number}
     * @memberof StorageListRequest
     */
    limit?: number;
    /**
     * Pagination cursor from previous response
     * @type {string}
     * @memberof StorageListRequest
     */
    cursor?: string;
}

/**
 * Check if a given object implements the StorageListRequest interface.
 */
export function instanceOfStorageListRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageListRequestFromJSON(json: any): StorageListRequest {
    return StorageListRequestFromJSONTyped(json, false);
}

export function StorageListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageListRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'prefix': !exists(json, 'prefix') ? undefined : json['prefix'],
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'cursor': !exists(json, 'cursor') ? undefined : json['cursor'],
    };
}

export function StorageListRequestToJSON(value?: StorageListRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'prefix': value.prefix,
        'limit': value.limit,
        'cursor': value.cursor,
    };
}

