/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface StorageMove200Response
 */
export interface StorageMove200Response {
    /**
     * 
     * @type {boolean}
     * @memberof StorageMove200Response
     */
    success?: boolean;
    /**
     * CDN URL of the file at its new location
     * @type {string}
     * @memberof StorageMove200Response
     */
    url?: string;
}

/**
 * Check if a given object implements the StorageMove200Response interface.
 */
export function instanceOfStorageMove200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageMove200ResponseFromJSON(json: any): StorageMove200Response {
    return StorageMove200ResponseFromJSONTyped(json, false);
}

export function StorageMove200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageMove200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function StorageMove200ResponseToJSON(value?: StorageMove200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'url': value.url,
    };
}

