/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface StorageUpload200Response
 */
export interface StorageUpload200Response {
    /**
     * 
     * @type {string}
     * @memberof StorageUpload200Response
     */
    url?: string;
}

/**
 * Check if a given object implements the StorageUpload200Response interface.
 */
export function instanceOfStorageUpload200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageUpload200ResponseFromJSON(json: any): StorageUpload200Response {
    return StorageUpload200ResponseFromJSONTyped(json, false);
}

export function StorageUpload200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageUpload200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function StorageUpload200ResponseToJSON(value?: StorageUpload200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
    };
}

