/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface StorageCopy200Response
 */
export interface StorageCopy200Response {
    /**
     * 
     * @type {boolean}
     * @memberof StorageCopy200Response
     */
    success?: boolean;
    /**
     * CDN URL of the new file
     * @type {string}
     * @memberof StorageCopy200Response
     */
    url?: string;
}

/**
 * Check if a given object implements the StorageCopy200Response interface.
 */
export function instanceOfStorageCopy200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageCopy200ResponseFromJSON(json: any): StorageCopy200Response {
    return StorageCopy200ResponseFromJSONTyped(json, false);
}

export function StorageCopy200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageCopy200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function StorageCopy200ResponseToJSON(value?: StorageCopy200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'url': value.url,
    };
}

