/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface StorageMoveRequest
 */
export interface StorageMoveRequest {
    /**
     * 
     * @type {string}
     * @memberof StorageMoveRequest
     */
    sourceKey: string;
    /**
     * 
     * @type {string}
     * @memberof StorageMoveRequest
     */
    destKey: string;
}

/**
 * Check if a given object implements the StorageMoveRequest interface.
 */
export function instanceOfStorageMoveRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "sourceKey" in value;
    isInstance = isInstance && "destKey" in value;

    return isInstance;
}

export function StorageMoveRequestFromJSON(json: any): StorageMoveRequest {
    return StorageMoveRequestFromJSONTyped(json, false);
}

export function StorageMoveRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageMoveRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sourceKey': json['sourceKey'],
        'destKey': json['destKey'],
    };
}

export function StorageMoveRequestToJSON(value?: StorageMoveRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sourceKey': value.sourceKey,
        'destKey': value.destKey,
    };
}

