/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
import type { StorageObject } from './StorageObject.js';
import {
    StorageObjectFromJSON,
    StorageObjectFromJSONTyped,
    StorageObjectToJSON,
} from './StorageObject.js';

/**
 * 
 * @export
 * @interface StorageListResult
 */
export interface StorageListResult {
    /**
     * 
     * @type {Array<StorageObject>}
     * @memberof StorageListResult
     */
    objects?: Array<StorageObject>;
    /**
     * True if more files exist beyond this page
     * @type {boolean}
     * @memberof StorageListResult
     */
    truncated?: boolean;
    /**
     * Use this cursor to fetch the next page
     * @type {string}
     * @memberof StorageListResult
     */
    cursor?: string;
}

/**
 * Check if a given object implements the StorageListResult interface.
 */
export function instanceOfStorageListResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageListResultFromJSON(json: any): StorageListResult {
    return StorageListResultFromJSONTyped(json, false);
}

export function StorageListResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageListResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'objects': !exists(json, 'objects') ? undefined : ((json['objects'] as Array<any>).map(StorageObjectFromJSON)),
        'truncated': !exists(json, 'truncated') ? undefined : json['truncated'],
        'cursor': !exists(json, 'cursor') ? undefined : json['cursor'],
    };
}

export function StorageListResultToJSON(value?: StorageListResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'objects': value.objects === undefined ? undefined : ((value.objects as Array<any>).map(StorageObjectToJSON)),
        'truncated': value.truncated,
        'cursor': value.cursor,
    };
}

