/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface StorageMetadata
 */
export interface StorageMetadata {
    /**
     * 
     * @type {boolean}
     * @memberof StorageMetadata
     */
    _exists?: boolean;
    /**
     * File size in bytes
     * @type {number}
     * @memberof StorageMetadata
     */
    size?: number;
    /**
     * 
     * @type {string}
     * @memberof StorageMetadata
     */
    contentType?: string;
    /**
     * 
     * @type {Date}
     * @memberof StorageMetadata
     */
    lastModified?: Date;
    /**
     * 
     * @type {string}
     * @memberof StorageMetadata
     */
    etag?: string;
}

/**
 * Check if a given object implements the StorageMetadata interface.
 */
export function instanceOfStorageMetadata(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageMetadataFromJSON(json: any): StorageMetadata {
    return StorageMetadataFromJSONTyped(json, false);
}

export function StorageMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageMetadata {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        '_exists': !exists(json, 'exists') ? undefined : json['exists'],
        'size': !exists(json, 'size') ? undefined : json['size'],
        'contentType': !exists(json, 'contentType') ? undefined : json['contentType'],
        'lastModified': !exists(json, 'lastModified') ? undefined : (new Date(json['lastModified'])),
        'etag': !exists(json, 'etag') ? undefined : json['etag'],
    };
}

export function StorageMetadataToJSON(value?: StorageMetadata | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'exists': value._exists,
        'size': value.size,
        'contentType': value.contentType,
        'lastModified': value.lastModified === undefined ? undefined : (value.lastModified.toISOString()),
        'etag': value.etag,
    };
}

