/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface StorageObject
 */
export interface StorageObject {
    /**
     * Storage key (project prefix stripped)
     * @type {string}
     * @memberof StorageObject
     */
    key?: string;
    /**
     * File size in bytes
     * @type {number}
     * @memberof StorageObject
     */
    size?: number;
    /**
     * 
     * @type {Date}
     * @memberof StorageObject
     */
    lastModified?: Date;
    /**
     * 
     * @type {string}
     * @memberof StorageObject
     */
    contentType?: string;
    /**
     * 
     * @type {string}
     * @memberof StorageObject
     */
    etag?: string;
}

/**
 * Check if a given object implements the StorageObject interface.
 */
export function instanceOfStorageObject(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageObjectFromJSON(json: any): StorageObject {
    return StorageObjectFromJSONTyped(json, false);
}

export function StorageObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': !exists(json, 'key') ? undefined : json['key'],
        'size': !exists(json, 'size') ? undefined : json['size'],
        'lastModified': !exists(json, 'lastModified') ? undefined : (new Date(json['lastModified'])),
        'contentType': !exists(json, 'contentType') ? undefined : json['contentType'],
        'etag': !exists(json, 'etag') ? undefined : json['etag'],
    };
}

export function StorageObjectToJSON(value?: StorageObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'size': value.size,
        'lastModified': value.lastModified === undefined ? undefined : (value.lastModified.toISOString()),
        'contentType': value.contentType,
        'etag': value.etag,
    };
}

