/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface TokenWallet
 */
export interface TokenWallet {
    /**
     * Remaining token balance
     * @type {number}
     * @memberof TokenWallet
     */
    balance?: number;
    /**
     * Total tokens consumed to date
     * @type {number}
     * @memberof TokenWallet
     */
    totalConsumed?: number;
}

/**
 * Check if a given object implements the TokenWallet interface.
 */
export function instanceOfTokenWallet(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TokenWalletFromJSON(json: any): TokenWallet {
    return TokenWalletFromJSONTyped(json, false);
}

export function TokenWalletFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenWallet {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'balance': !exists(json, 'balance') ? undefined : json['balance'],
        'totalConsumed': !exists(json, 'total_consumed') ? undefined : json['total_consumed'],
    };
}

export function TokenWalletToJSON(value?: TokenWallet | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'balance': value.balance,
        'total_consumed': value.totalConsumed,
    };
}

