/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface TokenUsage
 */
export interface TokenUsage {
    /**
     * Tokens in the prompt
     * @type {number}
     * @memberof TokenUsage
     */
    promptTokens?: number;
    /**
     * Tokens generated
     * @type {number}
     * @memberof TokenUsage
     */
    completionTokens?: number;
    /**
     * Total tokens consumed
     * @type {number}
     * @memberof TokenUsage
     */
    totalTokens?: number;
}

/**
 * Check if a given object implements the TokenUsage interface.
 */
export function instanceOfTokenUsage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TokenUsageFromJSON(json: any): TokenUsage {
    return TokenUsageFromJSONTyped(json, false);
}

export function TokenUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenUsage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'promptTokens': !exists(json, 'prompt_tokens') ? undefined : json['prompt_tokens'],
        'completionTokens': !exists(json, 'completion_tokens') ? undefined : json['completion_tokens'],
        'totalTokens': !exists(json, 'total_tokens') ? undefined : json['total_tokens'],
    };
}

export function TokenUsageToJSON(value?: TokenUsage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'prompt_tokens': value.promptTokens,
        'completion_tokens': value.completionTokens,
        'total_tokens': value.totalTokens,
    };
}

