/* tslint:disable */
/* eslint-disable */
/**
 * Aerostack API
 * Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface TypeStats
 */
export interface TypeStats {
    /**
     * 
     * @type {string}
     * @memberof TypeStats
     */
    type?: string;
    /**
     * 
     * @type {number}
     * @memberof TypeStats
     */
    count?: number;
}

/**
 * Check if a given object implements the TypeStats interface.
 */
export function instanceOfTypeStats(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TypeStatsFromJSON(json: any): TypeStats {
    return TypeStatsFromJSONTyped(json, false);
}

export function TypeStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypeStats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'count': !exists(json, 'count') ? undefined : json['count'],
    };
}

export function TypeStatsToJSON(value?: TypeStats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'count': value.count,
    };
}

